import test from 'node:test';import assert from 'node:assert/strict';import{mkdtemp,rm}from'node:fs/promises';import{tmpdir}from'node:os';import{join}from'node:path';import{defineAuth}from'../dist/auth.js';import{openComments,createCommentClient}from'../dist/comments.js';
async function fixture(){const root=await mkdtemp(join(tmpdir(),'clank-comments-')),options={path:join(root,'app.sqlite'),auth:defineAuth({password:{cost:1024,maxMemory:4*1024*1024}})};let service=await openComments(options);return{get service(){return service},async user(email){const r=await service.handle(new Request('https://comments.test/__clank/comments/auth/register',{method:'POST',headers:{'content-type':'application/json',origin:'https://comments.test'},body:JSON.stringify({email,password:'correct horse battery staple'})}));assert.equal(r.status,201);const data=await r.json(),cookie=r.headers.get('set-cookie').split(';',1)[0];return{id:data.user.id,client:createCommentClient({url:'https://comments.test/__clank/comments',auth:{csrfHeader:()=>({'x-clank-csrf':data.csrfToken})},fetch:(url,init)=>service.handle(new Request(url,{...init,headers:{...init.headers,cookie,origin:'https://comments.test'}}))})}},async restart(){service.close();service=await openComments(options)},async close(){service.close();await rm(root,{recursive:true,force:true})}}}
test('shared comments enforce resource roles, isolate outsiders, persist threads, fence edits, and immediately revoke cached access',async()=>{
 const app=await fixture();try{const alice=await app.user('alice@example.invalid'),bob=await app.user('bob@example.invalid'),reader=await app.user('reader@example.invalid');for(const [user,role]of[[alice,'commenter'],[bob,'moderator'],[reader,'reader']])app.service.setAccess('project-1',user.id,role);
 const root=await alice.client.add('project-1','Original',{key:'first'});assert.equal((await alice.client.add('project-1','Original',{key:'first'})).id,root.id);await assert.rejects(alice.client.add('project-1','Different',{key:'first'}));await assert.rejects(reader.client.add('project-1','Blocked'));await assert.rejects(bob.client.list('other-project'));
 const reply=await bob.client.add('project-1','Reply',{parentId:root.id});assert.equal((await reader.client.thread('project-1',root.id)).length,2);await assert.rejects(alice.client.edit('project-1',reply.id,'Not mine',reply.version));
 const edited=await bob.client.edit('project-1',root.id,'Moderated',root.version);await assert.rejects(alice.client.edit('project-1',root.id,'Stale',root.version));await bob.client.resolve('project-1',root.id,true,edited.version);await assert.rejects(alice.client.add('project-1','Late reply',{parentId:reply.id}));
 await app.restart();const thread=await bob.client.thread('project-1',root.id);assert.equal(thread[0].resolved,true);await bob.client.remove('project-1',reply.id,reply.version);const after=await alice.client.thread('project-1',root.id);assert.equal(after[1].deleted,true);assert.equal(after[1].body,'');
 assert.equal((await reader.client.list('project-1')).items.length,1);app.service.setAccess('project-1',reader.id,null);await assert.rejects(reader.client.list('project-1'));await assert.rejects(reader.client.thread('project-1',root.id));
 }finally{await app.close()}
});
test('comments cap nesting, paginate roots deterministically, and reject cross-resource parents',async()=>{
 const app=await fixture();try{const alice=await app.user('depth@example.invalid');app.service.setAccess('a',alice.id,'commenter');app.service.setAccess('b',alice.id,'commenter');let parent=await alice.client.add('a','Root');for(let i=0;i<4;i++)parent=await alice.client.add('a',`Depth ${i+1}`,{parentId:parent.id});await assert.rejects(alice.client.add('a','Too deep',{parentId:parent.id}));await assert.rejects(alice.client.add('b','Wrong resource',{parentId:parent.id}));
 for(let i=0;i<21;i++)await alice.client.add('a',`Thread ${i}`);const first=await alice.client.list('a');assert.equal(first.items.length,20);assert.ok(first.next);const second=await alice.client.list('a',first.next);assert.equal(second.items.length,2);assert.equal(new Set([...first.items,...second.items].map(item=>item.id)).size,22);
 }finally{await app.close()}
});
test('comment pagination does not drop or duplicate same-millisecond mixed-case IDs',async()=>{const app=await fixture(),clock=Date.now;try{const user=await app.user('ties@example.invalid');app.service.setAccess('ties',user.id,'commenter');const fixed=clock();Date.now=()=>fixed;for(let i=0;i<45;i++)await user.client.add('ties',`Entry ${i}`);let next,ids=[];do{const page=await user.client.list('ties',next);ids.push(...page.items.map(row=>row.id));next=page.next;}while(next);assert.equal(ids.length,45);assert.equal(new Set(ids).size,45);}finally{Date.now=clock;await app.close()}});
