import test from 'node:test';import assert from 'node:assert/strict';import{mkdtemp,rm}from'node:fs/promises';import{tmpdir}from'node:os';import{join}from'node:path';
import{defineDatabase,openSQLite}from'../dist/backend.js';import{openNodeEvacuations}from'../dist/node-evacuation.js';
const internal=Symbol.for('clank.sqlite.internal');
async function fixture(){const root=await mkdtemp(join(tmpdir(),'clank-evacuation-')),path=join(root,'db.sqlite');let db=await openSQLite(defineDatabase({}),{path});return{get plans(){return openNodeEvacuations(db[internal])},get sql(){return db[internal]},async reopen(){db.close();db=await openSQLite(defineDatabase({}),{path})},async close(){db.close();await rm(root,{recursive:true,force:true})}}}
const source=[{projectId:'project_one',releaseId:'release_one',generation:3},{projectId:'project_two',releaseId:'release_two',generation:6}];
function hooks(events,overrides={}){return{verify(){},drain(){events.push('drain')},async snapshot(project){events.push('stop+snapshot:'+project.projectId);return'bk_'+project.projectId},fence(){events.push('fence')},async relocate(project){events.push('relocate:'+project.projectId);return{nodeId:'target_node',generation:project.generation+1}},cancel(){events.push('cancel')},...overrides}}
test('evacuation requires every final snapshot before fencing, persists progress and resumes exactly',async()=>{const f=await fixture();try{const events=[],plan=f.plans.create('source_node','administrator',false,source);assert.throws(()=>f.plans.create('source_node','administrator',false,source),/unfinished/);assert.equal(f.plans.activeForProject('project_one'),true);let failed=false;await assert.rejects(f.plans.run(plan.id,hooks(events,{async snapshot(project){events.push('stop+snapshot:'+project.projectId);if(project.projectId==='project_two'&&!failed){failed=true;throw Error('snapshot transport failed')}return'bk_'+project.projectId}})),/snapshot transport failed/);assert.deepEqual(events,['drain','stop+snapshot:project_one','stop+snapshot:project_two']);assert.equal(f.plans.get(plan.id).state,'paused');assert.throws(()=>f.plans.cancel(plan.id,hooks(events)),/stopping writers/);await f.reopen();const completed=await f.plans.run(plan.id,hooks(events));assert.equal(completed.state,'completed');assert.deepEqual(events.slice(3),['stop+snapshot:project_two','fence','relocate:project_one','relocate:project_two']);assert.equal(f.plans.activeForProject('project_one'),false);await f.plans.run(plan.id,hooks(events));assert.equal(events.length,7);}finally{await f.close()}});
test('evacuation pauses after fencing and never restarts source writers when target recovery fails',async()=>{const f=await fixture();try{const events=[],plan=f.plans.create('source_node','administrator',true,source);await assert.rejects(f.plans.run(plan.id,hooks(events,{async relocate(project){events.push('relocate:'+project.projectId);throw Error('capacity vanished')}})),/capacity vanished/);assert.equal(f.plans.get(plan.id).phase,'relocating');assert.equal(f.plans.get(plan.id).state,'paused');await f.reopen();await f.plans.run(plan.id,hooks(events));assert.equal(events.filter(value=>value==='fence').length,1);assert.equal(events.filter(value=>value.startsWith('stop+')).length,2);}finally{await f.close()}});
test('evacuation cancellation is allowed only before quiescing, with current authorization and exclusive execution',async()=>{const f=await fixture();try{const events=[],plan=f.plans.create('source_node','administrator',false,source);assert.throws(()=>f.plans.cancel(plan.id,hooks(events,{verify(){throw Error('revoked')}})),/revoked/);assert.equal(f.plans.cancel(plan.id,hooks(events)).state,'cancelled');const next=f.plans.create('source_node','administrator',false,source);let release;const wait=new Promise(resolve=>{release=resolve});const executing=f.plans.run(next.id,hooks(events,{async snapshot(project){await wait;return'bk_'+project.projectId}}));await new Promise(resolve=>setImmediate(resolve));await assert.rejects(f.plans.run(next.id,hooks(events)),/already running/);assert.throws(()=>f.plans.cancel(next.id,hooks(events)),/stopping writers/);release();await executing;}finally{await f.close()}});
test('lost execution lease and revoked authority prevent later destructive stages',async()=>{const f=await fixture();try{const events=[],plan=f.plans.create('source_node','administrator',false,source);await assert.rejects(f.plans.run(plan.id,hooks(events,{async snapshot(project){f.sql.prepare('UPDATE clank_platform_evacuations SET lease_id=? WHERE id=?').run('successor',plan.id);return'bk_'+project.projectId}})),/lease was lost/);assert.deepEqual(events,['drain']);assert.equal(f.plans.get(plan.id).projects[0].backupId,null);}finally{await f.close()}});
