import test from 'node:test';import assert from 'node:assert/strict';import{mkdtemp,rm}from'node:fs/promises';import{tmpdir}from'node:os';import{join}from'node:path';
import{defineDatabase,defineTable,openSQLite}from'../dist/backend.js';import{defineAuth}from'../dist/auth.js';import{s}from'../dist/ai.js';import{openRecordHistory,createRecordHistoryClient,compareRecordVersions}from'../dist/record-history.js';
test('structural comparisons distinguish removal/null, escape pointer paths, preserve arrays and enforce limits',()=>{
 const result=compareRecordVersions({name:'Old',removed:true,optional:null,'a/b':1,array:[1]},{name:'New',optional:null,'a/b':2,array:[2],added:null});assert.deepEqual(result.changes.map(c=>[c.path,c.kind]),[['/a~1b','changed'],['/added','added'],['/array','changed'],['/name','changed'],['/removed','removed']]);assert.equal(result.truncated,false);
 assert.equal(compareRecordVersions({a:1,b:2},{a:2,b:3},1).truncated,true);assert.equal(compareRecordVersions({a:1,b:2},{b:2,a:1}).changes.length,0);assert.throws(()=>compareRecordVersions('x'.repeat(70000),{}),/64 KiB/);
 const left=JSON.parse('{"__proto__":{"x":1}}'),right=JSON.parse('{"__proto__":{"x":2}}');assert.equal(compareRecordVersions(left,right).changes[0].path,'/__proto__/x');assert.equal({}.x,undefined);
});
test('record history isolates owners, pages retained snapshots, and restores through an atomic business guard with version conflicts',async()=>{
 const root=await mkdtemp(join(tmpdir(),'clank-history-ui-')),path=join(root,'app.sqlite'),schema=defineDatabase({notes:defineTable({title:s.string()}).owned()});let blocked=false;
 const service=await openRecordHistory({path,schema,auth:defineAuth({password:{cost:1024,maxMemory:4*1024*1024}}),tables:['notes'],validateRestore(){if(blocked)throw new Error('policy')}}),db=await openSQLite(schema,{path});
 const user=async email=>{const r=await service.handle(new Request('https://history.test/__clank/history/auth/register',{method:'POST',headers:{'content-type':'application/json',origin:'https://history.test'},body:JSON.stringify({email,password:'correct horse battery staple'})}));const data=await r.json(),cookie=r.headers.get('set-cookie').split(';',1)[0];return{id:data.user.id,client:createRecordHistoryClient({url:'https://history.test/__clank/history',auth:{csrfHeader:()=>({'x-clank-csrf':data.csrfToken})},fetch:(url,init)=>service.handle(new Request(url,{...init,headers:{...init.headers,cookie,origin:'https://history.test'}}))})}};
 try{const alice=await user('alice@example.invalid'),bob=await user('bob@example.invalid');const id=db.transaction(tx=>tx.table('notes').insert({title:'Original'}),{userId:alice.id});for(let i=0;i<30;i++)db.transaction(tx=>tx.table('notes').patch(id,{title:`Edit ${i}`} ),{userId:alice.id});
 const first=await alice.client.list('notes',id);assert.equal(first.entries.length,25);assert.ok(first.next);const second=await alice.client.list('notes',id,first.next);assert.equal(second.entries.length,6);const original=second.entries.at(-1);assert.deepEqual((await bob.client.list('notes',id)).entries,[]);await assert.rejects(bob.client.restore('notes',id,original.cursor,null));
 blocked=true;await assert.rejects(alice.client.restore('notes',id,original.cursor,first.current._version));assert.equal(db.read(tx=>tx.table('notes').get(id),{userId:alice.id}).title,'Edit 29');blocked=false;
 db.transaction(tx=>tx.table('notes').patch(id,{title:'Concurrent'}),{userId:alice.id});await assert.rejects(alice.client.restore('notes',id,original.cursor,first.current._version));const latest=await alice.client.list('notes',id);const restored=await alice.client.restore('notes',id,original.cursor,latest.current._version);assert.equal(restored._id,id);assert.equal(restored.title,'Original');assert.equal((await alice.client.list('notes',id)).entries[0].operation,'restore');
 }finally{service.close();db.close();await rm(root,{recursive:true,force:true})}
});
