// Packed CLI transport/plan contracts. These controlled HTTP responses do not
// establish native platform authorization; that is tested by the API suite.
import test from 'node:test';import assert from 'node:assert/strict';
import {execFile,spawn} from 'node:child_process';import {promisify} from 'node:util';
import {mkdtemp,mkdir,writeFile,rm} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';import {fileURLToPath} from 'node:url';import {createServer} from 'node:http';
const exec=promisify(execFile),repository=fileURLToPath(new URL('../',import.meta.url));
test('packed recovery CLI preserves exact checkpoint requests and prepares bounded current browser restores without submitting them',async t=>{
  const root=await mkdtemp(join(tmpdir(),'clank-recovery-cli-')),clientDirectory=join(root,'client'),work=join(root,'application'),calls=[],checkpointId='pitr_'+'a'.repeat(64);let version=1;
  const server=createServer(async(req,res)=>{let bytes='';for await(const part of req)bytes+=part;calls.push({method:req.method,path:req.url,body:bytes?JSON.parse(bytes):null});assert.equal(req.headers.authorization,'Bearer owned_cli_transport_fixture');res.setHeader('content-type','application/json');res.end(JSON.stringify(req.url.endsWith('/checkpoints')?{ok:true,checkpoint:{id:checkpointId,sequence:3}}:req.url.endsWith('/point-in-time')?{ok:true,policy:{version,enabled:true},checkpoints:[{id:checkpointId,epoch:'owned_epoch',sequence:3}],restores:[]}:{ok:true,project:{id:'project_exact',slug:'captured-source'}}));});
  await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const origin='http://127.0.0.1:'+server.address().port;
  t.after(async()=>{server.closeAllConnections();await new Promise(resolve=>server.close(resolve));await rm(root,{recursive:true,force:true});});
  const packed=JSON.parse((await exec('npm',['pack','--ignore-scripts','--json','--pack-destination',root],{cwd:repository,maxBuffer:4*1024*1024})).stdout),archive=Array.isArray(packed)?packed[0]:Object.values(packed)[0];
  await exec('tar',['-xf',join(root,archive.filename),'-C',root]);await mkdir(clientDirectory);await mkdir(join(work,'.clank'),{recursive:true});
  await writeFile(join(clientDirectory,'config.json'),JSON.stringify({version:1,current:origin,profiles:{[origin]:{token:'owned_cli_transport_fixture',expiresAt:Date.now()+120000}}}));await writeFile(join(work,'.clank/project.json'),JSON.stringify({version:1,server:origin,projectId:'project_exact'}));
  const invoke=args=>new Promise((resolve,reject)=>{const child=spawn(process.execPath,['--disable-warning=ExperimentalWarning',join(root,'package/scripts/clank.mjs'),'recovery',...args],{cwd:work,env:{...process.env,CLANK_HOME:clientDirectory},stdio:['ignore','pipe','pipe']});let stdout='',stderr='';child.stdout.on('data',value=>stdout+=value);child.stderr.on('data',value=>stderr+=value);child.once('error',reject);child.once('close',code=>resolve({code,stdout,stderr}));});
  const status=await invoke(['status','--json']);assert.equal(status.code,0,status.stderr);assert.equal(JSON.parse(status.stdout).checkpoints[0].sequence,3);
  for(let i=0;i<2;i++){const result=await invoke(['checkpoint','--key','exact_checkpoint_01','--expected-version','1','--json']);assert.equal(result.code,0,result.stderr);assert.equal(JSON.parse(result.stdout).checkpoint.id,checkpointId);assert.deepEqual(calls.at(-1),{method:'POST',path:'/api/projects/project_exact/point-in-time/checkpoints',body:{operationId:'exact_checkpoint_01',expectedVersion:1}});}
  const proposed={operationId:'exact_restore_01',checkpointId,expectedVersion:1,throughSequence:2,name:'Recovered point two',slug:'recovered-point-two'},file=join(root,'restore.json');await writeFile(file,JSON.stringify(proposed));
  const valid=await invoke(['restore-plan','--request',file,'--json']);assert.equal(valid.code,0,valid.stderr);const plan=JSON.parse(valid.stdout);assert.equal(plan.browserOnly,true);assert.equal(plan.method,'POST');assert.equal(plan.path,'/api/projects/project_exact/point-in-time/restores');assert.deepEqual(plan.request,{...proposed,confirmation:`restore-recovery captured-source ${checkpointId} 2 recovered-point-two`});assert.ok(calls.every(call=>call.path!==plan.path));
  for(const invalid of [{...proposed,throughSequence:4},{...proposed,expectedVersion:2},{...proposed,slug:'../destination'},{...proposed,operationId:'invalid operation'},{...proposed,extra:true}]){await writeFile(file,JSON.stringify(invalid));const before=calls.filter(call=>call.method==='POST').length,result=await invoke(['restore-plan','--request',file,'--json']);assert.equal(result.code,1);assert.equal(calls.filter(call=>call.method==='POST').length,before);}
  await writeFile(file,JSON.stringify(proposed));version=2;assert.equal((await invoke(['restore-plan','--request',file,'--json'])).code,1);
  for(const args of [['checkpoint','--key','exact_checkpoint_01','--json'],['checkpoint','--key','bad key','--expected-version','1','--json'],['status','--key','unused','--json'],['restore-plan','--json']]){const before=calls.length;assert.equal((await invoke(args)).code,1);assert.equal(calls.length,before);}
});
