import test from 'node:test';import assert from 'node:assert/strict';import{mkdtemp,rm}from'node:fs/promises';import{tmpdir}from'node:os';import{join}from'node:path';import{DatabaseSync}from'node:sqlite';
import{defineDatabase,defineTable,openSQLite}from'../dist/backend.js';import{defineAuth}from'../dist/auth.js';import{s}from'../dist/ai.js';import{openRecycleBin,createRecycleBinClient}from'../dist/recycle-bin.js';
async function fixture(extra={}){const root=await mkdtemp(join(tmpdir(),'clank-trash-')),path=join(root,'app.sqlite'),schema=defineDatabase({notes:defineTable({title:s.string(),body:s.string()}).owned()});const options={path,schema,auth:defineAuth({password:{cost:1024,maxMemory:4*1024*1024}}),tables:{notes:{labelField:'title'}},...extra};let bin=await openRecycleBin(options);const db=await openSQLite(schema,{path});
 return{path,db,get bin(){return bin},async user(email){const r=await bin.handle(new Request('https://trash.test/__clank/trash/auth/register',{method:'POST',headers:{'content-type':'application/json',origin:'https://trash.test'},body:JSON.stringify({email,password:'correct horse battery staple'})}));assert.equal(r.status,201);const data=await r.json(),cookie=r.headers.get('set-cookie').split(';',1)[0];return{id:data.user.id,client:createRecycleBinClient({url:'https://trash.test/__clank/trash',auth:{csrfHeader:()=>({'x-clank-csrf':data.csrfToken})},fetch:(url,init)=>bin.handle(new Request(url,{...init,headers:{...init.headers,cookie,origin:'https://trash.test'}}))})}},async restart(){bin.close();bin=await openRecycleBin(options)},async close(){bin.close();db.close();await rm(root,{recursive:true,force:true})}}}
test('recycle bin restores original IDs/ownership across restart, fences stale history, and permanently purges deleted snapshots',async()=>{
 const app=await fixture();try{const alice=await app.user('alice@example.invalid'),bob=await app.user('bob@example.invalid');const id=app.db.transaction(db=>db.table('notes').insert({title:'Recover me',body:'private'}),{userId:alice.id});
 await assert.rejects(bob.client.trash('notes',id,1));assert.equal(await alice.client.trash('notes',id,1),true);assert.deepEqual((await bob.client.list('notes')).items,[]);const item=(await alice.client.list('notes')).items[0];assert.equal(item.label,'Recover me');assert.equal(await bob.client.purge('notes',id,item.cursor),false);
 await app.restart();const restored=await alice.client.restore('notes',id,item.cursor);assert.equal(restored._id,id);assert.equal(restored._ownerId,alice.id);assert.equal(restored.body,'private');await assert.rejects(alice.client.purge('notes',id,item.cursor));
 await alice.client.trash('notes',id,restored._version);const again=(await alice.client.list('notes')).items[0];await assert.rejects(alice.client.restore('notes',id,item.cursor));assert.equal(await alice.client.purge('notes',id,again.cursor),true);assert.equal((await alice.client.list('notes')).items.length,0);await assert.rejects(alice.client.restore('notes',id,again.cursor));assert.deepEqual(app.db.read(db=>db.table('notes').history(id),{userId:alice.id}),[]);
 }finally{await app.close()}
});
test('expired trash cannot restore, bounded sweeps remove history, and application validators veto invalid recovery atomically',async()=>{
 let veto=true;const app=await fixture({retentionMs:1000,validateRestore(){if(veto)throw new Error('business rule')}});try{const alice=await app.user('expiry@example.invalid');const id=app.db.transaction(db=>db.table('notes').insert({title:'Expired',body:''}),{userId:alice.id});await alice.client.trash('notes',id,1);const item=(await alice.client.list('notes')).items[0];await assert.rejects(alice.client.restore('notes',id,item.cursor));assert.equal(app.db.read(db=>db.table('notes').get(id),{userId:alice.id}),null);veto=false;
 const sql=new DatabaseSync(app.path);sql.prepare('UPDATE clank_document_revisions SET recorded_at=0 WHERE document_id=?').run(id);sql.close();await assert.rejects(alice.client.restore('notes',id,item.cursor));assert.equal(app.bin.purgeExpired(1),1);assert.equal(app.bin.purgeExpired(1),0);assert.throws(()=>app.bin.purgeExpired(0),/Sweep/);
 }finally{await app.close()}
});
