import type { AuthDefinition } from "./auth.ts";
import type { SyncClientOptions } from "./backend.ts";
export interface ActivityCursor { at: number; id: string; }
export interface ActivityItem { id: string; title: string; detail: string; kind: string; href: string | null; at: number; read: boolean; }
export interface ActivityPage { items: readonly ActivityItem[]; next: ActivityCursor | null; unread: number; kinds: readonly string[]; }
export interface ActivityClient { list(options?: { before?: ActivityCursor; kind?: string; unreadOnly?: boolean }): Promise<ActivityPage>; markRead(id: string): Promise<void>; markThrough(cursor: ActivityCursor): Promise<void>; clearThrough(cursor: ActivityCursor): Promise<void>; }
export interface ActivityOptions { path: string; auth: AuthDefinition<any>; prefix?: string; maxEntries?: number; }
export interface ActivityService { handle(request: Request): Promise<Response>; record(userId: string, event: { key: string; title: string; detail?: string; kind?: string; href?: string }): string; close(): void; }
import { createApi, createSyncClient, defineBackend, defineDatabase, defineTable, openBackend } from "./backend.ts";
import { s } from "./ai.ts";
import { SQLITE_INTERNAL } from "./sqlite-internal.ts";
const cursorSchema=s.object({at:s.number({integer:true,min:0}),id:s.string({min:1,max:200})});
const eventSchema=s.object({key:s.string({min:1,max:128}),title:s.string({min:1,max:160}),detail:s.optional(s.string({max:1000})),kind:s.optional(s.string({min:1,max:40})),href:s.optional(s.string({max:2048}))});
const schema=defineDatabase({personalActivity:defineTable({key:s.string(),title:s.string(),detail:s.string(),kind:s.string(),href:s.nullable(s.string()),at:s.number(),read:s.boolean()}).owned().index("by_key",["key"])});
const compare=(a:any,b:any)=>b.at-a.at||(a._id===b._id?0:a._id<b._id?1:-1);
const through=(row:any,cursor:ActivityCursor)=>row.at<cursor.at||(row.at===cursor.at&&row._id<=cursor.id);
export async function openActivity(options:ActivityOptions):Promise<ActivityService> {
  const maximum=options.maxEntries??1000;if(!Number.isInteger(maximum)||maximum<25||maximum>5000)throw new TypeError("Activity retention must be 25–5,000 entries.");
  const backend=defineBackend({schema,auth:options.auth}).functions(({query,mutation})=>({
    list:query({args:{before:s.optional(cursorSchema),kind:s.optional(s.string({min:1,max:40})),unreadOnly:s.optional(s.boolean())},handler:({db},{before,kind,unreadOnly})=>{const all=db.table("personalActivity").collect(),rows=all.filter(row=>(!kind||row.kind===kind)&&(!unreadOnly||!row.read)&&(!before||row.at<before.at||row.at===before.at&&row._id<before.id)).sort(compare),page=rows.slice(0,25),last=page.at(-1);return{items:page.map(row=>({id:row._id,title:row.title,detail:row.detail,kind:row.kind,href:row.href,at:row.at,read:row.read})),next:rows.length>25?{at:last!.at,id:last!._id}:null,unread:all.filter(row=>!row.read).length,kinds:[...new Set(all.map(row=>row.kind))].sort()};}}),
    markRead:mutation({args:{id:s.string()},handler:({db},{id})=>{const table=db.table("personalActivity"),row=table.get(id);if(!row)throw new Error("Activity is unavailable.");if(!row.read)table.patch(id,{read:true});}}),
    markThrough:mutation({args:{cursor:cursorSchema},handler:({db},{cursor})=>{const table=db.table("personalActivity");for(const row of table.collect())if(!row.read&&through(row,cursor))table.patch(row._id,{read:true});}}),
    clearThrough:mutation({args:{cursor:cursorSchema},handler:({db},{cursor})=>{const table=db.table("personalActivity");for(const row of table.collect())if(through(row,cursor))table.delete(row._id);}}),
  }));const runtime=await openBackend(backend,{path:options.path,prefix:options.prefix??"__clank/activity"});return{handle:r=>runtime.handle(r),close:()=>runtime.close(),record(userId,event){
    const input=eventSchema.parse(event),title=input.title.trim(),kind=input.kind??"info",href=input.href??null;if(!title||!/^[a-z][a-z0-9.-]{0,39}$/u.test(kind)||href!==null&&(!href.startsWith("/")||href.startsWith("//")||/[\u0000-\u001f\u007f\\]/u.test(href)))throw new TypeError("Invalid activity title, kind, or app link.");
    return runtime.database.transaction(db=>{const user=runtime.database[SQLITE_INTERNAL].prepare("SELECT disabled FROM clank_auth_users WHERE id=?").get(userId);if(!user||Number(user.disabled))throw new Error("Activity account is unavailable.");const table=db.table("personalActivity"),existing=table.query().where("key",input.key).first();if(existing)return existing._id;const id=table.insert({key:input.key,title,detail:input.detail??"",kind,href,at:Date.now(),read:false});for(const row of table.collect().sort(compare).slice(maximum))table.delete(row._id);return id;},{userId});
  }};
}
export function createActivityClient(options:SyncClientOptions={}):ActivityClient {
 const api=createApi<any>(),prefix=(options.url??"/__clank/activity").replace(/\/$/,""),transport=createSyncClient({...options,url:"",fetch:(url,init)=>(options.fetch??fetch)(`${prefix}${String(url).replace(/^\/__clank/,"")}`,init)});return{list:(input={})=>transport.query(api.list,input),markRead:id=>transport.mutate(api.markRead,{id}),markThrough:cursor=>transport.mutate(api.markThrough,{cursor}),clearThrough:cursor=>transport.mutate(api.clearThrough,{cursor})};
}
export function mountActivity(container:HTMLElement,client:ActivityClient):()=>void {
 const doc=container.ownerDocument,panel=doc.createElement("section"),status=doc.createElement("p"),kind=doc.createElement("select"),unread=doc.createElement("input"),label=doc.createElement("label"),list=doc.createElement("ol"),more=doc.createElement("button");panel.setAttribute("aria-label","Activity timeline");status.setAttribute("role","status");kind.setAttribute("aria-label","Activity kind");unread.type="checkbox";label.append(unread,"Unread only");more.type="button";more.textContent="Older activity";
 let closed=false,busy=false,next:ActivityCursor|null=null,latest:ActivityCursor|null=null;
 const button=(text:string,action:()=>Promise<void>)=>{const node=doc.createElement("button");node.type="button";node.textContent=text;node.onclick=()=>{void run(action)};return node;};
 const load=async(append=false)=>{const page=await client.list({before:append?next??undefined:undefined,kind:kind.value||undefined,unreadOnly:unread.checked});if(closed)return;const selected=kind.value;kind.replaceChildren();const all=doc.createElement("option");all.value="";all.textContent="All activity";kind.append(all);for(const value of page.kinds){const option=doc.createElement("option");option.value=option.textContent=value;kind.append(option);}kind.value=selected;next=page.next;if(!append){list.replaceChildren();latest=page.items[0]?{at:page.items[0].at,id:page.items[0].id}:null;}for(const row of page.items){const item=doc.createElement("li"),title=doc.createElement("strong"),detail=doc.createElement("p"),time=doc.createElement("p");title.textContent=row.title;detail.textContent=row.detail;time.textContent=`${new Date(row.at).toLocaleString()} · ${row.kind} · ${row.read?"Read":"Unread"}`;item.append(title,time,detail);if(row.href){const link=doc.createElement("a");link.href=row.href;link.textContent="Open related item";item.append(link);}if(!row.read)item.append(button("Mark read",async()=>{await client.markRead(row.id);await load();}));list.append(item);}more.hidden=!next;status.textContent=`${page.unread} unread activities.`;};
 const run=async(action:()=>Promise<void>)=>{if(closed||busy)return;busy=true;for(const node of panel.querySelectorAll("button,input,select"))(node as HTMLInputElement).disabled=true;try{await action();}catch{if(!closed)status.textContent="Could not load or update activity. Refresh and retry.";}finally{busy=false;for(const node of panel.querySelectorAll("button,input,select"))(node as HTMLInputElement).disabled=false;}};
 kind.onchange=unread.onchange=()=>{void run(()=>load())};more.onclick=()=>{if(next)void run(()=>load(true))};const clear=doc.createElement("details"),summary=doc.createElement("summary");summary.textContent="Clear older activity";clear.append(summary,"Clear all activity through the newest displayed entry, including other kinds.",button("Confirm clear",async()=>{if(latest){await client.clearThrough(latest);await load();}}));panel.append(kind,label,status,list,more,button("Mark through newest read",async()=>{if(latest){await client.markThrough(latest);await load();}}),clear,button("Refresh activity",()=>load()));container.append(panel);void run(()=>load());return()=>{closed=true;panel.remove();};
}
