import type { AuthDefinition } from "./auth.ts";
import type { SyncClientOptions } from "./backend.ts";
export interface TimeWindow { startAt: number; endAt: number; }
export interface AvailabilityWindow extends TimeWindow { id: string; title: string; version: number; }
export interface SlotOptions extends TimeWindow { durationMinutes: number; stepMinutes?: number; bufferMinutes?: number; blocked?: readonly TimeWindow[]; limit?: number; }
export interface AvailabilityClient { list(): Promise<readonly AvailabilityWindow[]>; save(input: { id?: string; expectedVersion?: number; title: string; startAt: number; endAt: number }): Promise<AvailabilityWindow>; remove(id: string, expectedVersion: number): Promise<void>; }
export interface AvailabilityOptions { path: string; auth: AuthDefinition<any>; prefix?: string; }
import { createApi, createSyncClient, defineBackend, defineDatabase, defineTable, openBackend } from "./backend.ts";
import { s } from "./ai.ts";
import { parseReminderTime } from "./reminders.ts";
const timestamp=s.number({integer:true,min:1,max:4102444800000});
const validWindow=(row:TimeWindow)=>{timestamp.parse(row.startAt);timestamp.parse(row.endAt);if(row.startAt>=row.endAt)throw new TypeError("Window end must follow its start.");};
/** Absolute-time slot calculation; merged windows avoid duplicates and half-open intervals allow adjacency. */
export function availableSlots(windows:readonly TimeWindow[],options:SlotOptions):{slots:readonly TimeWindow[];truncated:boolean} {
 validWindow(options);const duration=options.durationMinutes,step=options.stepMinutes??duration,buffer=options.bufferMinutes??0,limit=options.limit??1000;
 if(!Array.isArray(windows)||windows.length>1000||!Array.isArray(options.blocked??[])||(options.blocked?.length??0)>1000||options.endAt-options.startAt>31*86400000||![duration,step].every(value=>Number.isInteger(value)&&value>=1&&value<=1440)||!Number.isInteger(buffer)||buffer<0||buffer>1440||!Number.isInteger(limit)||limit<1||limit>5000)throw new TypeError("Invalid availability slot bounds.");
 const sorted=windows.map(row=>{validWindow(row);return{startAt:row.startAt,endAt:row.endAt};}).sort((a,b)=>a.startAt-b.startAt),merged:TimeWindow[]=[];
 for(const row of sorted){const last=merged.at(-1);if(last&&row.startAt<=last.endAt)last.endAt=Math.max(last.endAt,row.endAt);else merged.push(row);}
 const blocked=(options.blocked??[]).map(row=>{validWindow(row);return{startAt:row.startAt-buffer*60000,endAt:row.endAt+buffer*60000};}).sort((a,b)=>a.startAt-b.startAt),blockedMerged:TimeWindow[]=[],slots:TimeWindow[]=[];
 for(const row of blocked){const last=blockedMerged.at(-1);if(last&&row.startAt<=last.endAt)last.endAt=Math.max(last.endAt,row.endAt);else blockedMerged.push(row);}let blockedIndex=0;
 for(const window of merged){const end=Math.min(window.endAt,options.endAt),first=window.startAt+Math.max(0,Math.ceil((options.startAt-window.startAt)/(step*60000)))*step*60000;for(let start=first;start+duration*60000<=end;start+=step*60000){const candidate={startAt:start,endAt:start+duration*60000};while(blockedIndex<blockedMerged.length&&blockedMerged[blockedIndex]!.endAt<=candidate.startAt)blockedIndex++;if(blockedMerged[blockedIndex]&&blockedMerged[blockedIndex]!.startAt<candidate.endAt)continue;if(slots.length===limit)return{slots,truncated:true};slots.push(candidate);}}
 return{slots,truncated:false};
}
const schema=defineDatabase({personalAvailability:defineTable({title:s.string({min:1,max:100}),startAt:timestamp,endAt:timestamp}).owned()});
export async function openAvailability(options:AvailabilityOptions):Promise<{handle(request:Request):Promise<Response>;close():void}> {
 const view=(row:any):AvailabilityWindow=>({id:row._id,title:row.title,startAt:row.startAt,endAt:row.endAt,version:row._version});
 const backend=defineBackend({schema,auth:options.auth}).functions(({query,mutation})=>({
 list:query({args:{},handler:({db})=>db.table("personalAvailability").collect().sort((a,b)=>a.startAt-b.startAt||a._id.localeCompare(b._id)).map(view)}),
 save:mutation({args:{id:s.optional(s.string()),expectedVersion:s.optional(s.number({integer:true,min:1})),title:s.string({min:1,max:100}),startAt:timestamp,endAt:timestamp},handler:({db},input)=>{validWindow(input);const title=input.title.trim();if(!title||input.endAt-input.startAt>7*86400000)throw new Error("Availability needs a title and a duration of at most seven days.");const table=db.table("personalAvailability"),rows=table.collect();if(input.id){const current=table.get(input.id);if(!current||current._version!==input.expectedVersion)throw new Error("Availability changed or is unavailable.");}else if(input.expectedVersion!==undefined)throw new Error("New availability has no version.");
 const duplicate=rows.find(row=>row._id!==input.id&&row.startAt===input.startAt&&row.endAt===input.endAt);if(!input.id&&duplicate&&duplicate.title===title)return view(duplicate);if(rows.some(row=>row._id!==input.id&&input.startAt<row.endAt&&input.endAt>row.startAt))throw new Error("Availability overlaps an existing window.");const value={title,startAt:input.startAt,endAt:input.endAt};if(input.id)return view(table.patch(input.id,value,{ifVersion:input.expectedVersion}));if(rows.length>=200)throw new Error("Availability window limit reached.");return view(table.get(table.insert(value)));}}),
 remove:mutation({args:{id:s.string(),expectedVersion:s.number({integer:true,min:1})},handler:({db},{id,expectedVersion})=>{const table=db.table("personalAvailability"),row=table.get(id);if(!row||row._version!==expectedVersion)throw new Error("Availability changed or is unavailable.");table.delete(id,{ifVersion:expectedVersion});}}),
 }));const runtime=await openBackend(backend,{path:options.path,prefix:options.prefix??"__clank/availability"});return{handle:r=>runtime.handle(r),close:()=>runtime.close()};
}
export function createAvailabilityClient(options:SyncClientOptions={}):AvailabilityClient {const api=createApi<any>(),prefix=(options.url??"/__clank/availability").replace(/\/$/,""),transport=createSyncClient({...options,url:"",fetch:(url,init)=>(options.fetch??fetch)(`${prefix}${String(url).replace(/^\/__clank/,"")}`,init)});return{list:()=>transport.query(api.list,{}),save:input=>transport.mutate(api.save,input),remove:(id,expectedVersion)=>transport.mutate(api.remove,{id,expectedVersion})};}
export function mountAvailability(container:HTMLElement,client:AvailabilityClient,options:{blocked?():readonly TimeWindow[];onSelect?(slot:TimeWindow):void}={}):()=>void {
 const doc=container.ownerDocument,panel=doc.createElement("section"),monthLabel=doc.createElement("h2"),calendar=doc.createElement("div"),status=doc.createElement("p"),list=doc.createElement("ul"),slots=doc.createElement("div"),title=doc.createElement("input"),start=doc.createElement("input"),end=doc.createElement("input"),duration=doc.createElement("select");panel.setAttribute("aria-label","Availability calendar");status.setAttribute("role","status");calendar.style.cssText="display:grid;grid-template-columns:repeat(7,minmax(0,1fr));gap:4px";calendar.setAttribute("role","group");calendar.setAttribute("aria-label","Choose a day");title.setAttribute("aria-label","Availability title");title.maxLength=100;start.type=end.type="datetime-local";start.setAttribute("aria-label","Availability starts");end.setAttribute("aria-label","Availability ends");duration.setAttribute("aria-label","Slot duration");for(const value of [15,30,60]){const option=doc.createElement("option");option.value=String(value);option.textContent=`${value} minutes`;duration.append(option);}duration.value="30";
 let closed=false,busy=false,rows:readonly AvailabilityWindow[]=[],editing:AvailabilityWindow|undefined,day=new Date(),month=new Date(day.getFullYear(),day.getMonth(),1);
 const local=(at:number)=>{const date=new Date(at),pad=(n:number)=>String(n).padStart(2,"0");return`${date.getFullYear()}-${pad(date.getMonth()+1)}-${pad(date.getDate())}T${pad(date.getHours())}:${pad(date.getMinutes())}`;};
 const button=(text:string,action:()=>Promise<void>)=>{const node=doc.createElement("button");node.type="button";node.textContent=text;node.onclick=()=>{void run(action)};return node;};
 const render=()=>{monthLabel.textContent=month.toLocaleDateString(undefined,{month:"long",year:"numeric"});calendar.replaceChildren();for(const name of ["Sun","Mon","Tue","Wed","Thu","Fri","Sat"]){const label=doc.createElement("span");label.textContent=name;calendar.append(label);}for(let i=0;i<month.getDay();i++)calendar.append(doc.createElement("span"));const count=new Date(month.getFullYear(),month.getMonth()+1,0).getDate();for(let date=1;date<=count;date++){const value=new Date(month.getFullYear(),month.getMonth(),date),next=new Date(month.getFullYear(),month.getMonth(),date+1),has=rows.some(row=>row.startAt<next.getTime()&&row.endAt>value.getTime()),node=button(`${date}${has?" •":""}`,async()=>{day=value;render();});node.style.cssText="min-width:0;padding:8px 0;margin:0";node.setAttribute("aria-label",`${value.toLocaleDateString()}${has?", available":""}`);node.setAttribute("aria-pressed",String(day.toDateString()===value.toDateString()));calendar.append(node);}
 const from=new Date(day.getFullYear(),day.getMonth(),day.getDate()).getTime(),to=new Date(day.getFullYear(),day.getMonth(),day.getDate()+1).getTime();list.replaceChildren();for(const row of rows.filter(row=>row.startAt<to&&row.endAt>from)){const item=doc.createElement("li"),text=doc.createElement("p");text.textContent=`${row.title}: ${new Date(row.startAt).toLocaleString()} – ${new Date(row.endAt).toLocaleString()}`;item.append(text,button("Edit window",async()=>{editing=row;title.value=row.title;start.value=local(row.startAt);end.value=local(row.endAt);title.focus();}),button("Remove window",async()=>{await client.remove(row.id,row.version);if(editing?.id===row.id)reset();await load();}));list.append(item);}
 slots.replaceChildren();const result=availableSlots(rows,{startAt:Math.max(1,from),endAt:to,durationMinutes:Number(duration.value),blocked:options.blocked?.()??[],limit:100});for(const slot of result.slots)slots.append(button(new Date(slot.startAt).toLocaleTimeString(undefined,{hour:"2-digit",minute:"2-digit"}),async()=>{options.onSelect?.(slot);status.textContent="Time selected. This preview does not reserve it.";}));status.textContent=`${day.toLocaleDateString()}: ${result.slots.length}${result.truncated?"+":""} available slots. Times use this device’s zone.`;
 };
 const reset=()=>{editing=undefined;title.value=start.value=end.value="";};const load=async()=>{const result=await client.list();if(closed)return;rows=result;render();};
 const run=async(action:()=>Promise<void>)=>{if(closed||busy)return;busy=true;for(const node of panel.querySelectorAll("button,input,select"))(node as HTMLInputElement).disabled=true;try{await action();}catch{if(!closed)status.textContent="Could not save or show availability. Check dates, overlapping windows, or refresh after a conflict.";}finally{busy=false;for(const node of panel.querySelectorAll("button,input,select"))(node as HTMLInputElement).disabled=false;}};
 duration.onchange=()=>{void run(async()=>render())};panel.append(button("Previous month",async()=>{if(month.getFullYear()<=1970&&month.getMonth()===0)return;month=new Date(month.getFullYear(),month.getMonth()-1,1);day=month;render();}),monthLabel,button("Next month",async()=>{if(month.getFullYear()>=2099&&month.getMonth()===11)return;month=new Date(month.getFullYear(),month.getMonth()+1,1);day=month;render();}),calendar,duration,status,list,slots,title,start,end,button("Save availability",async()=>{await client.save({id:editing?.id,expectedVersion:editing?.version,title:title.value,startAt:parseReminderTime(start.value),endAt:parseReminderTime(end.value)});day=new Date(parseReminderTime(start.value));month=new Date(day.getFullYear(),day.getMonth(),1);reset();await load();}),button("Cancel edit",async()=>reset()),button("Refresh availability",load));container.append(panel);void run(load);return()=>{closed=true;panel.remove();};
}
