import type { AuthDefinition } from "./auth.ts";
import type { SyncClientOptions } from "./backend.ts";
export interface BookmarkFolder { id: string; name: string; version: number; }
export interface Bookmark { id: string; title: string; url: string; notes: string; folderId: string | null; favorite: boolean; version: number; }
export interface BookmarkState { folders: readonly BookmarkFolder[]; bookmarks: readonly Bookmark[]; }
export interface BookmarkClient { list(): Promise<BookmarkState>; save(input: { id?: string; expectedVersion?: number; title: string; url: string; notes?: string; folderId?: string | null; favorite?: boolean }): Promise<Bookmark>; remove(id: string, expectedVersion: number): Promise<void>; saveFolder(input: { id?: string; expectedVersion?: number; name: string }): Promise<BookmarkFolder>; removeFolder(id: string, expectedVersion: number): Promise<void>; }
export interface BookmarkOptions { path: string; auth: AuthDefinition<any>; prefix?: string; }
import { createApi, createSyncClient, defineBackend, defineDatabase, defineTable, openBackend } from "./backend.ts";
import { s } from "./ai.ts";
export function normalizeBookmarkUrl(value: string): string {
  if (typeof value !== "string" || value.length > 2048 || /[\u0000-\u001f\u007f\\]/u.test(value)) throw new TypeError("Invalid bookmark URL."); const text = value.trim(), relative = text.startsWith("/"); if (!text || text.startsWith("//")) throw new TypeError("Use an HTTP(S) URL or an app path.");
  const url = new URL(text,relative ? "https://clank.invalid" : undefined); if (!["http:","https:"].includes(url.protocol) || url.username || url.password || (relative && url.origin !== "https://clank.invalid")) throw new TypeError("Unsafe bookmark URL."); const normalized = relative ? url.pathname + url.search + url.hash : url.href; if (normalized.length > 2048) throw new TypeError("Bookmark URL is too long."); return normalized;
}
const schema = defineDatabase({ bookmarkFolders: defineTable({name:s.string({min:1,max:60})}).owned(), personalBookmarks: defineTable({title:s.string({min:1,max:160}),url:s.string({max:2048}),notes:s.string({max:500}),folderId:s.nullable(s.string()),favorite:s.boolean()}).owned().index("by_folder",["folderId"]) });
export async function openBookmarks(options: BookmarkOptions): Promise<{handle(request:Request):Promise<Response>;close():void}> {
  const folderView = (row:any):BookmarkFolder=>({id:row._id,name:row.name,version:row._version}), view=(row:any):Bookmark=>({id:row._id,title:row.title,url:row.url,notes:row.notes,folderId:row.folderId,favorite:row.favorite,version:row._version});
  const revision = {id:s.string(),expectedVersion:s.number({integer:true,min:1})};
  const backend=defineBackend({schema,auth:options.auth}).functions(({query,mutation})=>({
    list:query({args:{},handler:({db})=>({folders:db.table("bookmarkFolders").collect().sort((a,b)=>a.name.localeCompare(b.name)||a._id.localeCompare(b._id)).map(folderView),bookmarks:db.table("personalBookmarks").collect().sort((a,b)=>Number(b.favorite)-Number(a.favorite)||a.title.localeCompare(b.title)||a._id.localeCompare(b._id)).map(view)})}),
    save:mutation({args:{id:s.optional(s.string()),expectedVersion:s.optional(s.number({integer:true,min:1})),title:s.string({min:1,max:160}),url:s.string({min:1,max:2048}),notes:s.optional(s.string({max:500})),folderId:s.optional(s.nullable(s.string())),favorite:s.optional(s.boolean())},handler:({db},input)=>{
      const table=db.table("personalBookmarks"),title=input.title.trim(),url=normalizeBookmarkUrl(input.url),folderId=input.folderId??null;if(!title)throw new Error("Bookmark title is required.");if(folderId&&!db.table("bookmarkFolders").get(folderId))throw new Error("Folder is unavailable.");const duplicate=table.query().where("url",url).first();
      const value={title,url,notes:input.notes??"",folderId,favorite:input.favorite??false};if(input.id){const current=table.get(input.id);if(!current||current._version!==input.expectedVersion)throw new Error("Bookmark changed or is unavailable.");if(duplicate&&duplicate._id!==input.id)throw new Error("URL is already bookmarked.");return view(table.patch(input.id,value,{ifVersion:input.expectedVersion}));}
      if(input.expectedVersion!==undefined)throw new Error("New bookmark cannot have a version.");if(duplicate)return view(duplicate);if(table.collect().length>=500)throw new Error("Bookmark limit reached.");return view(table.get(table.insert(value)));
    }}),
    remove:mutation({args:revision,handler:({db},{id,expectedVersion})=>{const table=db.table("personalBookmarks"),row=table.get(id);if(!row||row._version!==expectedVersion)throw new Error("Bookmark changed or is unavailable.");table.delete(id,{ifVersion:expectedVersion});}}),
    saveFolder:mutation({args:{id:s.optional(s.string()),expectedVersion:s.optional(s.number({integer:true,min:1})),name:s.string({min:1,max:60})},handler:({db},input)=>{const table=db.table("bookmarkFolders"),name=input.name.trim().normalize("NFC"),rows=table.collect();if(!name)throw new Error("Folder name is required.");const duplicate=rows.find(row=>row.name.toLocaleLowerCase("en-US")===name.toLocaleLowerCase("en-US"));if(input.id){const row=table.get(input.id);if(!row||row._version!==input.expectedVersion||(duplicate&&duplicate._id!==input.id))throw new Error("Folder changed or name is unavailable.");return folderView(table.patch(input.id,{name},{ifVersion:input.expectedVersion}));}if(input.expectedVersion!==undefined)throw new Error("Invalid folder revision.");if(duplicate)return folderView(duplicate);if(rows.length>=50)throw new Error("Folder limit reached.");return folderView(table.get(table.insert({name})));}}),
    removeFolder:mutation({args:revision,handler:({db},{id,expectedVersion})=>{const table=db.table("bookmarkFolders"),row=table.get(id);if(!row||row._version!==expectedVersion)throw new Error("Folder changed or is unavailable.");for(const bookmark of db.table("personalBookmarks").query().where("folderId",id).collect())db.table("personalBookmarks").patch(bookmark._id,{folderId:null});table.delete(id,{ifVersion:expectedVersion});}}),
  }));const runtime=await openBackend(backend,{path:options.path,prefix:options.prefix??"__clank/bookmarks"});return{handle:r=>runtime.handle(r),close:()=>runtime.close()};
}
export function createBookmarkClient(options:SyncClientOptions={}):BookmarkClient {
  const api=createApi<any>(),prefix=(options.url??"/__clank/bookmarks").replace(/\/$/,""),transport=createSyncClient({...options,url:"",fetch:(url,init)=>(options.fetch??fetch)(`${prefix}${String(url).replace(/^\/__clank/,"")}`,init)});return{list:()=>transport.query(api.list,{}),save:input=>transport.mutate(api.save,{id:input.id,expectedVersion:input.expectedVersion,title:input.title,url:input.url,notes:input.notes,folderId:input.folderId,favorite:input.favorite}),remove:(id,expectedVersion)=>transport.mutate(api.remove,{id,expectedVersion}),saveFolder:input=>transport.mutate(api.saveFolder,input),removeFolder:(id,expectedVersion)=>transport.mutate(api.removeFolder,{id,expectedVersion})};
}
export function mountBookmarks(container:HTMLElement,client:BookmarkClient):()=>void {
  const doc=container.ownerDocument,panel=doc.createElement("section"),status=doc.createElement("p"),search=doc.createElement("input"),filter=doc.createElement("select"),folders=doc.createElement("select"),title=doc.createElement("input"),url=doc.createElement("input"),notes=doc.createElement("textarea"),folderName=doc.createElement("input"),list=doc.createElement("ul");panel.setAttribute("aria-label","Bookmarks");status.setAttribute("role","status");for(const[node,label,max]of[[search,"Search bookmarks",200],[title,"Bookmark title",160],[url,"Bookmark URL",2048],[notes,"Bookmark notes",500],[folderName,"Folder name",60]]as const){node.setAttribute("aria-label",label);node.maxLength=max;}filter.setAttribute("aria-label","Filter bookmarks");folders.setAttribute("aria-label","Bookmark folder");
  let closed=false,busy=false,state:BookmarkState={folders:[],bookmarks:[]},editing:Bookmark|undefined;
  const button=(text:string,action:()=>Promise<void>)=>{const node=doc.createElement("button");node.type="button";node.textContent=text;node.onclick=()=>{void run(action)};return node;};
  const reset=()=>{editing=undefined;title.value=url.value=notes.value="";folders.value="";};
  const render=()=>{list.replaceChildren();const query=search.value.toLocaleLowerCase(),rows=state.bookmarks.filter(row=>(filter.value==="all"||filter.value==="favorites"&&row.favorite||filter.value==="unfiled"&&!row.folderId||row.folderId===filter.value)&&`${row.title} ${row.url} ${row.notes}`.toLocaleLowerCase().includes(query));for(const row of rows){const item=doc.createElement("li"),link=doc.createElement("a"),description=doc.createElement("p");link.textContent=row.title;link.href=normalizeBookmarkUrl(row.url);link.rel="noopener noreferrer";description.textContent=row.notes;item.append(link,description,button(row.favorite?"Unfavorite":"Favorite",async()=>{await client.save({...row,expectedVersion:row.version,favorite:!row.favorite});await load();}),button("Edit bookmark",async()=>{editing=row;title.value=row.title;url.value=row.url;notes.value=row.notes;folders.value=row.folderId??"";title.focus();}));const details=doc.createElement("details"),summary=doc.createElement("summary");summary.textContent="Delete bookmark";details.append(summary,button("Confirm bookmark deletion",async()=>{await client.remove(row.id,row.version);if(editing?.id===row.id)reset();await load();}));item.append(details);list.append(item);}status.textContent=`${rows.length} bookmarks shown.`;};
  const load=async()=>{const result=await client.list();if(closed)return;state=result;const selected=filter.value,folder=folders.value;filter.replaceChildren();folders.replaceChildren();const option=(select:HTMLSelectElement,value:string,text:string)=>{const node=doc.createElement("option");node.value=value;node.textContent=text;select.append(node)};for(const[value,text]of[["all","All bookmarks"],["favorites","Favorites"],["unfiled","Unfiled"]])option(filter,value!,text!);option(folders,"","Unfiled");for(const row of state.folders){option(filter,row.id,row.name);option(folders,row.id,row.name);}filter.value=["all","favorites","unfiled",...state.folders.map(row=>row.id)].includes(selected)?selected:"all";folders.value=state.folders.some(row=>row.id===folder)?folder:"";render();};
  const run=async(action:()=>Promise<void>)=>{if(closed||busy)return;busy=true;for(const node of panel.querySelectorAll("button,input,textarea,select"))(node as HTMLInputElement).disabled=true;try{await action();}catch{if(!closed)status.textContent="Could not save. Check the URL and refresh after a conflict; your draft is preserved.";}finally{busy=false;for(const node of panel.querySelectorAll("button,input,textarea,select"))(node as HTMLInputElement).disabled=false;}};
  search.oninput=filter.onchange=render;const deleteFolder=doc.createElement("details"),summary=doc.createElement("summary");summary.textContent="Delete selected folder";deleteFolder.append(summary,"Bookmarks will move to Unfiled.",button("Confirm folder deletion",async()=>{const row=state.folders.find(row=>row.id===filter.value);if(!row)throw new Error("Choose a folder.");await client.removeFolder(row.id,row.version);await load();}));
  panel.append(search,filter,status,list,title,url,notes,folders,button("Save bookmark",async()=>{await client.save({id:editing?.id,expectedVersion:editing?.version,title:title.value,url:url.value,notes:notes.value,folderId:folders.value||null,favorite:editing?.favorite??false});reset();await load();}),button("Cancel edit",async()=>reset()),folderName,button("Create folder",async()=>{await client.saveFolder({name:folderName.value});folderName.value="";await load();}),button("Rename selected folder",async()=>{const row=state.folders.find(row=>row.id===filter.value);if(!row)throw new Error("Choose a folder.");await client.saveFolder({id:row.id,expectedVersion:row.version,name:folderName.value});folderName.value="";await load();}),deleteFolder,button("Refresh bookmarks",load));container.append(panel);void run(load);return()=>{closed=true;panel.remove();};
}
