export interface PaletteCommand { id: string; title: string; category?: string; keywords?: readonly string[]; enabled?: () => boolean; run(context: { signal: AbortSignal }): void | Promise<void>; }
export interface CommandPalette { open(): void; close(): void; setCommands(commands: readonly PaletteCommand[]): void; dispose(): void; }
const fold = (text: string) => text.normalize("NFKD").replace(/\p{M}/gu, "").toLocaleLowerCase("en-US");
function checked(commands: readonly PaletteCommand[]): readonly PaletteCommand[] {
  if (!Array.isArray(commands) || commands.length > 500) throw new TypeError("A palette supports at most 500 commands."); const ids = new Set<string>();
  return commands.map(command => { if (!command || typeof command.id !== "string" || !command.id || command.id.length > 100 || ids.has(command.id) || typeof command.title !== "string" || !command.title.trim() || command.title.length > 100 || typeof command.run !== "function" || (command.enabled !== undefined && typeof command.enabled !== "function") || (command.category !== undefined && (typeof command.category !== "string" || command.category.length > 80)) || (command.keywords !== undefined && (!Array.isArray(command.keywords) || command.keywords.length > 20 || command.keywords.some(word => typeof word !== "string" || word.length > 80)))) throw new TypeError("Invalid or duplicate palette command."); ids.add(command.id); return Object.freeze({ ...command, keywords: command.keywords ? Object.freeze([...command.keywords]) : undefined }); });
}
/** Accent-insensitive AND search; exact titles and title prefixes rank before keywords. */
export function searchCommands(commands: readonly PaletteCommand[], query: string, limit = 20): readonly PaletteCommand[] {
  if (typeof query !== "string" || query.length > 200 || !Number.isInteger(limit) || limit < 1 || limit > 100) throw new TypeError("Invalid command search bounds."); const rows = checked(commands), phrase = fold(query.trim()), words = phrase.split(/\s+/u).filter(Boolean); if (words.length > 12) return [];
  return rows.flatMap((command,index) => { let enabled = true; try { enabled = command.enabled?.() ?? true; } catch { enabled = false; } if (!enabled) return []; const title = fold(command.title), other = fold(`${command.category ?? ""} ${(command.keywords ?? []).join(" ")}`); if (!words.every(word => title.includes(word) || other.includes(word))) return [];
    const score = title === phrase ? 1000 : title.startsWith(phrase) && phrase ? 500 : words.reduce((total,word)=>total+(title.includes(word)?20:1),0); return [{command,index,score}];
  }).sort((a,b)=>b.score-a.score || a.index-b.index).slice(0,limit).map(row=>row.command);
}
/** Modal command search with focus restoration, keyboard selection, and cancellable async work. */
export function mountCommandPalette(container: HTMLElement, commands: readonly PaletteCommand[], options: { title?: string; onError?(error: unknown): void } = {}): CommandPalette {
  let catalog = checked(commands); const doc = container.ownerDocument, openButton = doc.createElement("button"), dialog = doc.createElement("dialog"), heading = doc.createElement("h2"), input = doc.createElement("input"), results = doc.createElement("div"), status = doc.createElement("p"), closeButton = doc.createElement("button"), id = `clank-palette-${crypto.randomUUID()}`;
  openButton.type = closeButton.type = "button"; openButton.textContent = "Commands"; closeButton.textContent = "Close commands"; heading.textContent = options.title ?? "Commands"; heading.id = `${id}-title`; dialog.setAttribute("aria-labelledby",heading.id); dialog.style.maxWidth = "calc(100vw - 40px)"; dialog.style.width = "560px"; input.style.width = "100%"; input.style.boxSizing = "border-box";
  input.type = "search"; input.maxLength = 200; input.setAttribute("aria-label","Search commands"); input.setAttribute("role","combobox"); input.setAttribute("aria-autocomplete","list"); input.setAttribute("aria-controls",`${id}-results`); results.id = `${id}-results`; results.setAttribute("role","listbox"); results.setAttribute("aria-label","Matching commands"); results.style.maxHeight = "50vh"; results.style.overflowY = "auto"; status.setAttribute("role","status");
  let closed = false, busy = false, selected = 0, matches: readonly PaletteCommand[] = [], previous: HTMLElement | null = null, controller: AbortController | undefined, generation = 0;
  const render = () => { matches = searchCommands(catalog,input.value); selected = Math.max(0,Math.min(selected,matches.length-1)); results.replaceChildren();
    matches.forEach((command,index) => { const item = doc.createElement("button"); item.type = "button"; item.tabIndex = -1; item.setAttribute("role","option"); item.setAttribute("aria-selected",String(index===selected)); item.id = `${id}-option-${index}`; item.style.display = "block"; item.style.width = "100%"; item.style.textAlign = "start"; item.style.overflowWrap = "anywhere"; item.textContent = `${command.title}${command.category ? ` · ${command.category}` : ""}`; item.disabled = busy; item.onclick = () => { selected = index; void execute(); }; results.append(item); });
    input.setAttribute("aria-expanded",String(dialog.open)); if (matches.length) input.setAttribute("aria-activedescendant",`${id}-option-${selected}`); else input.removeAttribute("aria-activedescendant"); status.textContent = matches.length ? `${matches.length} matching commands. Use arrow keys and Enter.` : "No matching commands.";
  };
  const close = () => { generation++; controller?.abort(); controller = undefined; busy = false; input.disabled = false; dialog.removeAttribute("aria-busy"); if (dialog.open) dialog.close(); input.setAttribute("aria-expanded","false"); if (previous?.isConnected) previous.focus(); };
  const execute = async () => { if (closed || busy || !dialog.open) return; const command = matches[selected]; if (!command) return; try { if (command.enabled && !command.enabled()) { render(); return; } } catch { render(); return; }
    busy = true; const current = ++generation; controller = new AbortController(); input.disabled = true; dialog.setAttribute("aria-busy","true"); for (const item of results.querySelectorAll("button")) item.disabled = true; status.textContent = `Running ${command.title}…`;
    try { await command.run({signal:controller.signal}); if (!closed && generation===current) close(); }
    catch (error) { if (!closed && generation===current) { busy = false; input.disabled = false; dialog.removeAttribute("aria-busy"); render(); status.textContent = "Command failed. You can retry or choose another command."; input.focus(); try { options.onError?.(error); } catch {} } }
  };
  input.oninput = () => { selected = 0; render(); }; input.onkeydown = event => { if (event.isComposing || busy) return; if (["ArrowDown","ArrowUp","Home","End"].includes(event.key)) { event.preventDefault(); selected = event.key === "Home" ? 0 : event.key === "End" ? matches.length-1 : (selected + (event.key==="ArrowDown"?1:-1) + matches.length) % Math.max(1,matches.length); render(); doc.getElementById(`${id}-option-${selected}`)?.scrollIntoView({block:"nearest"}); } else if (event.key === "Enter") { event.preventDefault(); void execute(); } };
  dialog.addEventListener("cancel",event=>{event.preventDefault();close();}); closeButton.onclick = close;
  const open = () => { if (closed || dialog.open) return; previous = doc.activeElement as HTMLElement | null; input.value = ""; selected = 0; dialog.showModal(); render(); input.focus(); };
  openButton.onclick = open; dialog.append(heading,input,results,status,closeButton); container.append(openButton,dialog);
  return { open, close, setCommands(next) { const validated = checked(next); catalog = validated; if (dialog.open && !busy) render(); }, dispose() { if (closed) return; close(); closed = true; openButton.remove(); dialog.remove(); } };
}
