import type { AuthDefinition } from "./auth.ts";
import type { SyncClientOptions } from "./backend.ts";
export interface DashboardPlacement { id: string; visible: boolean; span: 1 | 2; collapsed: boolean; }
export interface DashboardLayout { id: string; name: string; widgets: readonly DashboardPlacement[]; isDefault: boolean; version: number; }
export interface DashboardClient { list(): Promise<readonly DashboardLayout[]>; save(input: { id?: string; expectedVersion?: number; name: string; widgets: readonly DashboardPlacement[] }): Promise<DashboardLayout>; remove(id: string, expectedVersion: number): Promise<void>; setDefault(id: string | null): Promise<void>; }
export interface DashboardOptions { path: string; auth: AuthDefinition<any>; widgetIds: readonly string[]; prefix?: string; }
export interface DashboardWidget { id: string; title: string; mount(container: HTMLElement): void | (() => void); }
import { createApi, createSyncClient, defineBackend, defineDatabase, defineTable, openBackend } from "./backend.ts";
import { s } from "./ai.ts";
const placement=s.object({id:s.string({min:1,max:100}),visible:s.boolean(),span:s.number({integer:true,min:1,max:2}),collapsed:s.boolean()});
function registry(ids:readonly string[]):readonly string[]{if(!Array.isArray(ids)||!ids.length||ids.length>30||ids.some(id=>typeof id!=="string"||!id||id.length>100)||new Set(ids).size!==ids.length)throw new TypeError("Register 1–30 unique dashboard widgets.");return[...ids];}
export function validateDashboardLayout(value:unknown,widgetIds:readonly string[]):readonly DashboardPlacement[]{const allowed=registry(widgetIds),parsed=s.array(placement,{max:30}).parse(value);if(parsed.some(row=>!allowed.includes(row.id))||new Set(parsed.map(row=>row.id)).size!==parsed.length)throw new TypeError("Dashboard layout contains unknown or duplicate widgets.");return Object.freeze([...parsed.map(row=>Object.freeze({...row}) as DashboardPlacement),...allowed.filter(id=>!parsed.some(row=>row.id===id)).map(id=>Object.freeze({id,visible:false,span:1 as const,collapsed:false}))]);}
const schema=defineDatabase({personalDashboardLayouts:defineTable({name:s.string({min:1,max:80}),widgets:s.array(placement,{max:30}),isDefault:s.boolean()}).owned()});
export async function openDashboardLayouts(options:DashboardOptions):Promise<{handle(request:Request):Promise<Response>;close():void}>{const allowed=registry(options.widgetIds),view=(row:any):DashboardLayout=>({id:row._id,name:row.name,widgets:validateDashboardLayout(row.widgets.filter((item:any)=>allowed.includes(item.id)),allowed),isDefault:row.isDefault,version:row._version});
 const backend=defineBackend({schema,auth:options.auth}).functions(({query,mutation})=>({list:query({args:{},handler:({db})=>db.table("personalDashboardLayouts").collect().sort((a,b)=>a.name.localeCompare(b.name)||a._id.localeCompare(b._id)).map(view)}),save:mutation({args:{id:s.optional(s.string()),expectedVersion:s.optional(s.number({integer:true,min:1})),name:s.string({min:1,max:80}),widgets:s.array(placement,{max:30})},handler:({db},input)=>{const widgets=validateDashboardLayout(input.widgets,allowed),name=input.name.trim().normalize("NFC"),table=db.table("personalDashboardLayouts"),rows=table.collect();if(!name||rows.some(row=>row._id!==input.id&&row.name.toLocaleLowerCase("en-US")===name.toLocaleLowerCase("en-US")))throw new Error("Choose a unique layout name.");if(input.id){const row=table.get(input.id);if(!row||row._version!==input.expectedVersion)throw new Error("Layout changed or is unavailable.");return view(table.patch(input.id,{name,widgets},{ifVersion:input.expectedVersion}));}if(input.expectedVersion!==undefined||rows.length>=20)throw new Error("Layout limit reached or invalid revision.");return view(table.get(table.insert({name,widgets,isDefault:false})));}}),remove:mutation({args:{id:s.string(),expectedVersion:s.number({integer:true,min:1})},handler:({db},{id,expectedVersion})=>{const table=db.table("personalDashboardLayouts"),row=table.get(id);if(!row||row._version!==expectedVersion)throw new Error("Layout changed or is unavailable.");table.delete(id,{ifVersion:expectedVersion});}}),setDefault:mutation({args:{id:s.nullable(s.string())},handler:({db},{id})=>{const table=db.table("personalDashboardLayouts");if(id&&!table.get(id))throw new Error("Layout is unavailable.");for(const row of table.collect())if(row.isDefault!==(row._id===id))table.patch(row._id,{isDefault:row._id===id});}})}));const runtime=await openBackend(backend,{path:options.path,prefix:options.prefix??"__clank/dashboard-layouts"});return{handle:r=>runtime.handle(r),close:()=>runtime.close()};}
export function createDashboardClient(options:SyncClientOptions={}):DashboardClient{const api=createApi<any>(),prefix=(options.url??"/__clank/dashboard-layouts").replace(/\/$/,""),transport=createSyncClient({...options,url:"",fetch:(url,init)=>(options.fetch??fetch)(`${prefix}${String(url).replace(/^\/__clank/,"")}`,init)});return{list:()=>transport.query(api.list,{}),save:input=>transport.mutate(api.save,input),remove:(id,expectedVersion)=>transport.mutate(api.remove,{id,expectedVersion}),setDefault:id=>transport.mutate(api.setDefault,{id})};}
export function mountDashboard(container:HTMLElement,client:DashboardClient,widgets:readonly DashboardWidget[]):()=>void{
 const ids=registry(widgets.map(widget=>widget.id));for(const widget of widgets)if(!widget.title||widget.title.length>100||typeof widget.mount!=="function")throw new TypeError("Invalid dashboard widget.");const doc=container.ownerDocument,panel=doc.createElement("section"),choose=doc.createElement("select"),name=doc.createElement("input"),status=doc.createElement("p"),customize=doc.createElement("details"),summary=doc.createElement("summary"),controls=doc.createElement("div"),grid=doc.createElement("div");panel.setAttribute("aria-label","Customizable dashboard");choose.setAttribute("aria-label","Dashboard layout");name.setAttribute("aria-label","Layout name");name.maxLength=80;status.setAttribute("role","status");summary.textContent="Customize widgets";customize.append(summary,controls);grid.style.cssText="display:grid;grid-template-columns:minmax(0,1fr);gap:16px";
 const defaults=()=>widgets.map(widget=>({id:widget.id,visible:true,span:1 as 1|2,collapsed:false}));let draft:DashboardPlacement[]=defaults(),layouts:readonly DashboardLayout[]=[],current:DashboardLayout|undefined,closed=false,busy=false,columns=1;
 const cards=new Map<string,{node:HTMLElement;body:HTMLElement;toggle:HTMLButtonElement;mounted:boolean;cleanup?:()=>void}>();
 const button=(text:string,action:()=>Promise<void>)=>{const node=doc.createElement("button");node.type="button";node.textContent=text;node.onclick=()=>{void run(action)};return node;};
 const sizes=()=>{grid.style.gridTemplateColumns=`repeat(${columns},minmax(0,1fr))`;for(const item of draft){const card=cards.get(item.id);if(card)card.node.style.gridColumn=`span ${Math.min(item.span,columns)}`;}};
 const render=()=>{controls.replaceChildren();for(const [index,item]of draft.entries()){const widget=widgets.find(widget=>widget.id===item.id)!,row=doc.createElement("div"),label=doc.createElement("label"),visible=doc.createElement("input"),wide=doc.createElement("input"),wideLabel=doc.createElement("label");visible.type=wide.type="checkbox";visible.checked=item.visible;wide.checked=item.span===2;label.append(visible,widget.title);wideLabel.append(wide,"Wide");visible.onchange=()=>{item.visible=visible.checked;render();status.textContent="Unsaved layout changes."};wide.onchange=()=>{item.span=wide.checked?2:1;sizes();status.textContent="Unsaved layout changes."};const move=(offset:number)=>async()=>{[draft[index],draft[index+offset]]=[draft[index+offset]!,draft[index]!];render();status.textContent="Unsaved layout changes."};const up=button("Move up",move(-1)),down=button("Move down",move(1));up.dataset.boundary=String(index===0);down.dataset.boundary=String(index===draft.length-1);up.disabled=index===0;down.disabled=index===draft.length-1;row.append(label,wideLabel,up,down);controls.append(row);
  let card=cards.get(item.id);if(!card){const node=doc.createElement("article"),heading=doc.createElement("h2"),body=doc.createElement("div"),toggle=button("",async()=>{const placement=draft.find(row=>row.id===item.id)!;placement.collapsed=!placement.collapsed;render();status.textContent="Unsaved layout changes."});toggle.dataset.dashboardToggle="true";heading.textContent=widget.title;node.style.minWidth="0";node.style.overflowWrap="anywhere";node.append(heading,toggle,body);card={node,body,toggle,mounted:false};cards.set(item.id,card);}card.node.hidden=!item.visible;card.body.hidden=item.collapsed;card.toggle.textContent=`${item.collapsed?"Expand":"Collapse"} ${widget.title}`;card.toggle.setAttribute("aria-expanded",String(!item.collapsed));if(item.visible&&!item.collapsed&&!card.mounted){card.mounted=true;try{card.cleanup=widget.mount(card.body)||undefined;}catch{card.body.textContent="Widget could not load.";}}grid.append(card.node);
 }sizes();};
 const apply=(layout?:DashboardLayout)=>{current=layout;draft=layout?validateDashboardLayout(layout.widgets,ids).map(item=>({...item})):defaults();name.value=layout?.name??"";choose.value=layout?.id??"";render();status.textContent=layout?`Loaded ${layout.name}${layout.isDefault?" (default)":""}.`:"Default widget arrangement.";};
 const load=async(selected?:string)=>{const rows=await client.list();if(closed)return;layouts=rows;choose.replaceChildren();const empty=doc.createElement("option");empty.value="";empty.textContent="New layout";choose.append(empty);for(const layout of layouts){const option=doc.createElement("option");option.value=layout.id;option.textContent=layout.name+(layout.isDefault?" (default)":"");choose.append(option);}apply(selected?layouts.find(row=>row.id===selected):layouts.find(row=>row.isDefault));};
 const run=async(action:()=>Promise<void>)=>{if(closed||busy)return;busy=true;for(const node of panel.querySelectorAll("button,input,select"))if(!grid.contains(node)||(node as HTMLElement).dataset.dashboardToggle==="true")(node as HTMLInputElement).disabled=true;try{await action();}catch{if(!closed)status.textContent="Could not save this layout. Your arrangement remains; refresh after a conflict.";}finally{busy=false;for(const node of panel.querySelectorAll("button,input,select"))if(!grid.contains(node)||(node as HTMLElement).dataset.dashboardToggle==="true")(node as HTMLInputElement).disabled=(node as HTMLElement).dataset.boundary==="true";}};
 choose.onchange=()=>apply(layouts.find(row=>row.id===choose.value));const deletion=doc.createElement("details"),deleteSummary=doc.createElement("summary");deleteSummary.textContent="Delete saved layout";deletion.append(deleteSummary,button("Confirm layout deletion",async()=>{if(current){await client.remove(current.id,current.version);current=undefined;await load();}}));
 panel.append(choose,name,button("Save layout",async()=>{const saved=await client.save({id:current?.id,expectedVersion:current?.version,name:name.value,widgets:draft});await load(saved.id);}),button("Save as new layout",async()=>{const saved=await client.save({name:name.value,widgets:draft});await load(saved.id);}),button("Use as default",async()=>{if(!current)throw new Error("Save the layout first.");await client.setDefault(current.id);await load(current.id);}),button("Reset arrangement",async()=>{draft=defaults();render();status.textContent="Default arrangement restored. Save to keep it.";}),button("Refresh layouts",()=>load(current?.id)),deletion,status,customize,grid);container.append(panel);void run(()=>load());const observer=typeof ResizeObserver!=="undefined"?new ResizeObserver(entries=>{columns=(entries[0]?.contentRect.width??0)>=640?2:1;sizes();}):undefined;observer?.observe(grid);
 return()=>{if(closed)return;closed=true;observer?.disconnect();for(const card of cards.values()){try{card.cleanup?.();}catch{}}panel.remove();};
}
