import type { AuthDefinition } from "./auth.ts";
import type { SyncClientOptions } from "./backend.ts";
export type FeedbackRole = "reader" | "voter" | "moderator";
export type FeedbackStatus = "proposed" | "planned" | "doing" | "done" | "declined" | "withdrawn";
export interface FeedbackIdea { id: string; title: string; body: string; status: FeedbackStatus; votes: number; voted: boolean; version: number; authorId: string; canEdit: boolean; }
export interface FeedbackBoard { ideas: readonly FeedbackIdea[]; canVote: boolean; moderator: boolean; }
export interface FeedbackClient { list(board: string): Promise<FeedbackBoard>; add(board: string, title: string, body: string, key?: string): Promise<string>; edit(board: string, id: string, title: string, body: string, expectedVersion: number): Promise<void>; vote(board: string, id: string, selected: boolean): Promise<void>; setStatus(board: string, id: string, status: FeedbackStatus, expectedVersion: number): Promise<void>; }
export interface FeedbackOptions { path: string; auth: AuthDefinition<any>; prefix?: string; }
export interface FeedbackService { handle(request: Request): Promise<Response>; setAccess(board: string, userId: string, role: FeedbackRole | null): void; close(): void; }
import { createApi, createSyncClient, defineBackend, defineDatabase, defineTable, openBackend } from "./backend.ts";
import { s } from "./ai.ts";
import { SQLITE_INTERNAL } from "./sqlite-internal.ts";
const boardSchema=s.string({min:1,max:200}),statusSchema=s.enum(["proposed","planned","doing","done","declined","withdrawn"]);
const schema=defineDatabase({feedbackMembers:defineTable({board:boardSchema,role:s.enum(["reader","voter","moderator"])}).owned().index("by_board",["board"]),feedbackIdeas:defineTable({board:boardSchema,authorId:s.string(),title:s.string({max:160}),body:s.string({max:2000}),status:statusSchema,votes:s.number({integer:true,min:0}),revision:s.number({integer:true,min:1}),key:s.string({max:128})}).index("by_board",["board"]),feedbackVotes:defineTable({board:boardSchema,idea:s.string()}).owned().index("by_board",["board"]).index("by_idea",["idea"])});
export async function openFeedback(options:FeedbackOptions):Promise<FeedbackService> {
 const access=(db:any,board:string,write=false):FeedbackRole=>{const member=db.table("feedbackMembers").query().where("board",board).first();if(!member||(write&&member.role==="reader"))throw new Error("Feedback access is unavailable.");return member.role;};
 const idea=(db:any,board:string,id:string)=>{const row=db.table("feedbackIdeas").get(id);if(!row||row.board!==board)throw new Error("Idea is unavailable.");return row;};
 const editArgs={board:boardSchema,id:s.string(),expectedVersion:s.number({integer:true,min:1})};
 const backend=defineBackend({schema,auth:options.auth}).functions(({query,mutation})=>({
  list:query({args:{board:boardSchema},handler:({db,user},{board})=>{const role=access(db,board),votes=new Set(db.table("feedbackVotes").query().where("board",board).collect().map(row=>row.idea));return{ideas:db.table("feedbackIdeas").query().where("board",board).collect().sort((a,b)=>b.votes-a.votes||a._creationTime-b._creationTime||a._id.localeCompare(b._id)).map(row=>({id:row._id,title:row.title,body:row.body,status:row.status,votes:row.votes,voted:votes.has(row._id),version:row.revision,authorId:row.authorId,canEdit:role==="moderator"||(role==="voter"&&row.authorId===user!.id&&row.status==="proposed")})),canVote:role!=="reader",moderator:role==="moderator"};}}),
  add:mutation({args:{board:boardSchema,title:s.string({min:1,max:160}),body:s.string({min:1,max:2000}),key:s.string({min:1,max:128})},handler:({db,user},{board,title,body,key})=>{access(db,board,true);title=title.trim();body=body.trim();if(!title||!body)throw new Error("Describe the idea before posting.");const table=db.table("feedbackIdeas"),rows=table.query().where("board",board).collect(),existing=rows.find(row=>row.authorId===user!.id&&row.key===key);if(existing)return existing._id;if(rows.length>=200)throw new Error("Feedback board limit reached.");return table.insert({board,authorId:user!.id,title,body,status:"proposed",votes:0,revision:1,key});}}),
  edit:mutation({args:{...editArgs,title:s.string({min:1,max:160}),body:s.string({min:1,max:2000})},handler:({db,user},{board,id,title,body,expectedVersion})=>{const role=access(db,board,true),row=idea(db,board,id);if(row.revision!==expectedVersion||(role!=="moderator"&&(row.authorId!==user!.id||row.status!=="proposed"))||!title.trim()||!body.trim())throw new Error("Idea changed or cannot be edited.");db.table("feedbackIdeas").patch(id,{title:title.trim(),body:body.trim(),revision:row.revision+1});}}),
  vote:mutation({args:{board:boardSchema,id:s.string(),selected:s.boolean()},handler:({db},{board,id,selected})=>{access(db,board,true);const row=idea(db,board,id),table=db.table("feedbackVotes"),existing=table.query().where("idea",id).first();if(selected){if(existing)return;if(!["proposed","planned","doing"].includes(row.status))throw new Error("Voting is closed for this idea.");table.insert({board,idea:id});db.table("feedbackIdeas").patch(id,{votes:row.votes+1});}else if(existing){table.delete(existing._id);db.table("feedbackIdeas").patch(id,{votes:Math.max(0,row.votes-1)});}}}),
  setStatus:mutation({args:{...editArgs,status:statusSchema},handler:({db,user},{board,id,status,expectedVersion})=>{const role=access(db,board,true),row=idea(db,board,id);if(row.revision!==expectedVersion||(role!=="moderator"&&!(row.authorId===user!.id&&row.status==="proposed"&&status==="withdrawn")))throw new Error("Idea status changed or cannot be managed.");db.table("feedbackIdeas").patch(id,{status,revision:row.revision+1});}}),
 }));const runtime=await openBackend(backend,{path:options.path,prefix:options.prefix??"__clank/feedback"});return{handle:r=>runtime.handle(r),close:()=>runtime.close(),setAccess(board,userId,role){boardSchema.parse(board);if(role!==null&&!["reader","voter","moderator"].includes(role))throw new TypeError("Invalid feedback role.");runtime.database.transaction(db=>{const user=runtime.database[SQLITE_INTERNAL].prepare("SELECT disabled FROM clank_auth_users WHERE id=?").get(userId);if(!user||Number(user.disabled))throw new Error("Feedback account is unavailable.");const table=db.table("feedbackMembers"),row=table.query().where("board",board).first();if(role===null){if(row)table.delete(row._id);}else if(row)table.patch(row._id,{role});else{if(table.collect().length>=2000)throw new Error("Feedback membership limit reached.");table.insert({board,role});}},{userId});}};
}
export function createFeedbackClient(options:SyncClientOptions={}):FeedbackClient {
 const api=createApi<any>(),prefix=(options.url??"/__clank/feedback").replace(/\/$/,""),transport=createSyncClient({...options,url:"",fetch:(url,init)=>(options.fetch??fetch)(`${prefix}${String(url).replace(/^\/__clank/,"")}`,init)});return{list:board=>transport.query(api.list,{board}),add:(board,title,body,key=crypto.randomUUID())=>transport.mutate(api.add,{board,title,body,key}),edit:(board,id,title,body,expectedVersion)=>transport.mutate(api.edit,{board,id,title,body,expectedVersion}),vote:(board,id,selected)=>transport.mutate(api.vote,{board,id,selected}),setStatus:(board,id,status,expectedVersion)=>transport.mutate(api.setStatus,{board,id,status,expectedVersion})};
}
export function mountFeedback(container:HTMLElement,client:FeedbackClient,board:string):()=>void {
 const doc=container.ownerDocument,panel=doc.createElement("section"),status=doc.createElement("p"),search=doc.createElement("input"),filter=doc.createElement("select"),title=doc.createElement("input"),body=doc.createElement("textarea"),list=doc.createElement("ol"),post=doc.createElement("button");panel.setAttribute("aria-label","Feedback board");status.setAttribute("role","status");for(const[node,label,max]of[[search,"Search ideas",200],[title,"Idea title",160],[body,"Idea description",2000]]as const){node.setAttribute("aria-label",label);node.maxLength=max;}filter.setAttribute("aria-label","Idea status");for(const value of ["all","proposed","planned","doing","done","declined","withdrawn"]){const option=doc.createElement("option");option.value=option.textContent=value;filter.append(option);}post.type="button";post.textContent="Post idea";
 let closed=false,busy=false,state:FeedbackBoard={ideas:[],canVote:false,moderator:false},key=crypto.randomUUID();
 const button=(text:string,action:()=>Promise<void>)=>{const node=doc.createElement("button");node.type="button";node.textContent=text;node.onclick=()=>{void run(action)};return node;};
 const render=()=>{list.replaceChildren();const query=search.value.toLocaleLowerCase(),rows=state.ideas.filter(row=>(filter.value==="all"||row.status===filter.value)&&`${row.title} ${row.body}`.toLocaleLowerCase().includes(query));for(const row of rows){const item=doc.createElement("li"),heading=doc.createElement("h3"),text=doc.createElement("p"),meta=doc.createElement("p");heading.textContent=row.title;text.textContent=row.body;meta.textContent=`${row.votes} votes · ${row.status}`;item.append(heading,text,meta);if(state.canVote&&(row.voted||["proposed","planned","doing"].includes(row.status)))item.append(button(row.voted?"Remove my vote":"Vote for idea",async()=>{await client.vote(board,row.id,!row.voted);await load();}));
  if(row.canEdit){const details=doc.createElement("details"),summary=doc.createElement("summary"),editTitle=doc.createElement("input"),editBody=doc.createElement("textarea");summary.textContent="Edit idea";editTitle.value=row.title;editBody.value=row.body;editTitle.maxLength=160;editBody.maxLength=2000;editTitle.setAttribute("aria-label","Edit idea title");editBody.setAttribute("aria-label","Edit idea description");details.append(summary,editTitle,editBody,button("Save idea edit",async()=>{await client.edit(board,row.id,editTitle.value,editBody.value,row.version);await load();}));item.append(details);}
  if(state.moderator){const select=doc.createElement("select");select.setAttribute("aria-label",`${row.title} status`);for(const value of ["proposed","planned","doing","done","declined","withdrawn"]){const option=doc.createElement("option");option.value=option.textContent=value;select.append(option);}select.value=row.status;item.append(select,button("Update status",async()=>{await client.setStatus(board,row.id,select.value as FeedbackStatus,row.version);await load();}));}else if(row.canEdit&&row.status==="proposed")item.append(button("Withdraw my idea",async()=>{await client.setStatus(board,row.id,"withdrawn",row.version);await load();}));list.append(item);}title.hidden=body.hidden=post.hidden=!state.canVote;status.textContent=`${rows.length} ideas shown, ordered by votes.`;};
 const load=async()=>{const result=await client.list(board);if(closed)return;state=result;render();};const run=async(action:()=>Promise<void>)=>{if(closed||busy)return;busy=true;for(const node of panel.querySelectorAll("button,input,textarea,select"))(node as HTMLInputElement).disabled=true;try{await action();}catch{if(!closed){state={ideas:[],canVote:false,moderator:false};list.replaceChildren();status.textContent="Could not complete this action. Refresh access or retry your preserved draft.";}}finally{busy=false;for(const node of panel.querySelectorAll("button,input,textarea,select"))(node as HTMLInputElement).disabled=false;}};
 search.oninput=filter.onchange=render;title.oninput=body.oninput=()=>{key=crypto.randomUUID()};post.onclick=()=>{void run(async()=>{await client.add(board,title.value,body.value,key);title.value=body.value="";key=crypto.randomUUID();await load();})};panel.append(search,filter,status,list,title,body,post,button("Refresh board",load));container.append(panel);void run(load);return()=>{closed=true;panel.remove();};
}
