import type {SQLiteInternal} from "./sqlite-internal.ts";
export interface SecretRotation { readonly id:string;readonly name:string;readonly state:string;readonly revision:string;readonly validation:string|null;readonly createdAt:number;readonly validatedAt:number|null; }
export interface SecretRevision { readonly name:string;readonly revision:string|null; }
export interface SecretRotationManager {
 stage(projectId:string,name:string,value:string):SecretRotation;
 validate(projectId:string,id:string):Promise<SecretRotation>;
 activate(projectId:string,id:string):SecretRotation;
 rollback(projectId:string,id:string):SecretRotation;
 list(projectId:string):readonly SecretRotation[];
 revisions(projectId:string,values?:Readonly<Record<string,string>>):readonly SecretRevision[];
}
export interface SecretRotationOptions { encrypt(value:string):string;decrypt(value:string):string;validate?:(input:{projectId:string;name:string;value:string;signal:AbortSignal})=>Promise<boolean>; }
/** Trusted control-plane storage; candidate and previous values are always encrypted. */
export async function openSecretRotations(sql:SQLiteInternal,options:SecretRotationOptions):Promise<SecretRotationManager>{
 const{createHash}=await import("node:crypto");const revision=(encrypted:string)=>createHash("sha256").update(encrypted).digest("hex");
 sql.exec("CREATE TABLE IF NOT EXISTS clank_platform_secret_rotations (id TEXT PRIMARY KEY,project_id TEXT NOT NULL REFERENCES clank_platform_projects(id) ON DELETE CASCADE,name TEXT NOT NULL,candidate TEXT NOT NULL,previous TEXT,base_revision TEXT,state TEXT NOT NULL,validation TEXT,validation_nonce TEXT,created_at INTEGER NOT NULL,validated_at INTEGER)");
 sql.exec("CREATE INDEX IF NOT EXISTS clank_secret_rotations_project ON clank_platform_secret_rotations(project_id,created_at DESC)");
 const current=(project:string,name:string)=>sql.prepare("SELECT encrypted_value FROM clank_platform_secrets WHERE project_id=? AND name=?").get(project,name);
 const read=(project:string,id:string)=>{const row=sql.prepare("SELECT * FROM clank_platform_secret_rotations WHERE project_id=? AND id=?").get(project,id);if(!row)throw new Error("SECRET_ROTATION_NOT_FOUND");return row;};
 const view=(row:Record<string,unknown>):SecretRotation=>Object.freeze({id:String(row.id),name:String(row.name),state:String(row.state),revision:revision(String(row.candidate)),validation:row.validation===null?null:String(row.validation),createdAt:Number(row.created_at),validatedAt:row.validated_at===null?null:Number(row.validated_at)});
 const unchanged=(row:Record<string,unknown>,expected:string|null)=>{const actual=current(String(row.project_id),String(row.name));if((actual?revision(String(actual.encrypted_value)):null)!==expected)throw new Error("SECRET_ROTATION_CONFLICT");};
 const write=(project:string,name:string,encrypted:string|null)=>{if(encrypted===null)sql.prepare("DELETE FROM clank_platform_secrets WHERE project_id=? AND name=?").run(project,name);else sql.prepare("INSERT INTO clank_platform_secrets(project_id,name,encrypted_value,updated_at) VALUES(?,?,?,?) ON CONFLICT(project_id,name) DO UPDATE SET encrypted_value=excluded.encrypted_value,updated_at=excluded.updated_at").run(project,name,encrypted,Date.now());};
 const manager:SecretRotationManager={
 stage(projectId,name,value){if(!/^[A-Z_][A-Z0-9_]{0,127}$/.test(name)||typeof value!=="string"||new TextEncoder().encode(value).length>65536)throw new TypeError("Invalid secret candidate.");let result!:SecretRotation;
  sql.transaction(changes=>{const count=Number(sql.prepare("SELECT count(*) AS count FROM clank_platform_secret_rotations WHERE project_id=?").get(projectId)?.count??0);if(count>=1000)throw new Error("SECRET_ROTATION_CAPACITY");const old=current(projectId,name),encrypted=options.encrypt(value),id=crypto.randomUUID();sql.prepare("INSERT INTO clank_platform_secret_rotations(id,project_id,name,candidate,previous,base_revision,state,created_at) VALUES(?,?,?,?,?,?,'staged',?)").run(id,projectId,name,encrypted,old?.encrypted_value??null,old?revision(String(old.encrypted_value)):null,Date.now());changes.record("__platform",projectId);result=view(read(projectId,id));});return result;
 },
 async validate(projectId,id){const row=read(projectId,id);if(row.state==="validating" && Date.now()-Number(row.validated_at)>15000)sql.prepare("UPDATE clank_platform_secret_rotations SET state='failed',validation_nonce=NULL WHERE id=? AND state='validating' AND validated_at=?").run(id,row.validated_at);else if(!["staged","validated","failed"].includes(String(row.state)))throw new Error("SECRET_ROTATION_STATE");const nonce=crypto.randomUUID();sql.prepare("UPDATE clank_platform_secret_rotations SET state='validating',validation_nonce=?,validated_at=? WHERE id=? AND state IN ('staged','validated','failed')").run(nonce,Date.now(),id);if(read(projectId,id).validation_nonce!==nonce)throw new Error("SECRET_ROTATION_CONFLICT");
  const controller=new AbortController();let timer:ReturnType<typeof setTimeout>|undefined;let ok=false;
  try{const value=options.decrypt(String(row.candidate));ok=options.validate?await Promise.race([options.validate({projectId,name:String(row.name),value,signal:controller.signal}),new Promise<false>(resolve=>{timer=setTimeout(()=>{controller.abort();resolve(false);},10000);})]):typeof value==="string";}
  catch{ok=false;}finally{if(timer)clearTimeout(timer);controller.abort();}
  sql.prepare("UPDATE clank_platform_secret_rotations SET state=?,validation=?,validated_at=?,validation_nonce=NULL WHERE id=? AND validation_nonce=? AND state='validating'").run(ok?"validated":"failed",options.validate?"provider-check":"format-and-encryption",ok?Date.now():null,id,nonce);return view(read(projectId,id));
 },
 activate(projectId,id){let result!:SecretRotation;sql.transaction(changes=>{const row=read(projectId,id);if(row.state!=="validated"||Date.now()-Number(row.validated_at)>15*60000)throw new Error("SECRET_ROTATION_REVALIDATE");unchanged(row,row.base_revision===null?null:String(row.base_revision));write(projectId,String(row.name),String(row.candidate));sql.prepare("UPDATE clank_platform_secret_rotations SET state='previous' WHERE project_id=? AND name=? AND state='active'").run(projectId,row.name);sql.prepare("UPDATE clank_platform_secret_rotations SET state='active' WHERE id=?").run(id);changes.record("__platform",projectId);result=view(read(projectId,id));});return result;},
 rollback(projectId,id){let result!:SecretRotation;sql.transaction(changes=>{const row=read(projectId,id);if(row.state!=="active")throw new Error("SECRET_ROTATION_STATE");unchanged(row,revision(String(row.candidate)));write(projectId,String(row.name),row.previous===null?null:String(row.previous));sql.prepare("UPDATE clank_platform_secret_rotations SET state='rolled-back' WHERE id=?").run(id);sql.prepare("UPDATE clank_platform_secret_rotations SET state='active' WHERE project_id=? AND name=? AND candidate=? AND state='previous'").run(projectId,row.name,row.previous);changes.record("__platform",projectId);result=view(read(projectId,id));});return result;},
 list(projectId){return Object.freeze(sql.prepare("SELECT * FROM clank_platform_secret_rotations WHERE project_id=? ORDER BY created_at DESC,id DESC LIMIT 1000").all(projectId).map(view));},
 revisions(projectId,values){const currentRows=sql.prepare("SELECT name,encrypted_value FROM clank_platform_secrets WHERE project_id=?").all(projectId);if(values===undefined)return Object.freeze(currentRows.map(row=>Object.freeze({name:String(row.name),revision:revision(String(row.encrypted_value))})));
  const history=sql.prepare("SELECT name,candidate,previous FROM clank_platform_secret_rotations WHERE project_id=? ORDER BY created_at DESC LIMIT 1000").all(projectId);
  const names=new Set([...currentRows.map(row=>String(row.name)),...history.map(row=>String(row.name))]);return Object.freeze([...names].filter(name=>Object.hasOwn(values,name)).map(name=>{const candidates=[...currentRows.filter(row=>row.name===name).map(row=>row.encrypted_value),...history.filter(row=>row.name===name).flatMap(row=>[row.candidate,row.previous])].filter((value):value is string=>typeof value==="string");const match=candidates.find(encrypted=>options.decrypt(encrypted)===values[name]);return Object.freeze({name,revision:match?revision(match):null});}));},
 };return manager;
}
