export interface TourStep { id: string; title: string; body: string; target(): Element | null; prepare?(signal: AbortSignal): void | Promise<void>; }
export interface TourProgress { version: string; stepId: string; status: "active" | "completed" | "skipped"; }
export interface TourController { start(restart?: boolean): Promise<void>; next(): Promise<void>; back(): Promise<void>; pause(): void; skip(): void; progress(): TourProgress; dispose(): void; }
export interface TourOptions { id: string; version: string; steps: readonly TourStep[]; storage?: Pick<Storage,"getItem"|"setItem">; onFinish?(status: "completed" | "skipped"): void; }
export function restoreTourProgress(snapshot: string | null, version: string, stepIds: readonly string[]): TourProgress {
  if (!version || version.length > 100 || !stepIds.length || stepIds.length > 50 || stepIds.some(id=>typeof id !== "string" || !id || id.length > 100) || new Set(stepIds).size !== stepIds.length) throw new TypeError("Invalid tour identity or steps.");
  const initial: TourProgress = { version, stepId: stepIds[0]!, status:"active" }; if (!snapshot || snapshot.length > 1000) return initial;
  try { const data = JSON.parse(snapshot); if (data?.version === version && stepIds.includes(data.stepId) && ["active","completed","skipped"].includes(data.status)) return {version,stepId:data.stepId,status:data.status}; } catch {} return initial;
}
/** Resumable, non-modal tours that highlight real host elements and report unavailable targets. */
export function createTour(document: Document, options: TourOptions): TourController {
  if (!options.id || options.id.length > 150) throw new TypeError("Invalid tour ID."); const steps = options.steps.map(step=>({...step})), ids = steps.map(step=>step.id);
  restoreTourProgress(null,options.version,ids); for (const step of steps) if (!step.title || step.title.length > 100 || !step.body || step.body.length > 1000 || typeof step.target !== "function" || (step.prepare !== undefined && typeof step.prepare !== "function")) throw new TypeError("Invalid tour step.");
  const key = `clank-tour:${options.id}`, panel = document.createElement("section"), heading = document.createElement("h2"), body = document.createElement("p"), status = document.createElement("p"), backButton = document.createElement("button"), nextButton = document.createElement("button"), retry = document.createElement("button"), pauseButton = document.createElement("button"), skipButton = document.createElement("button");
  const titleId = `clank-tour-${crypto.randomUUID()}`; heading.id = titleId; panel.setAttribute("role","dialog"); panel.setAttribute("aria-labelledby",titleId); status.setAttribute("role","status"); panel.style.cssText = "position:fixed;z-index:2147483000;bottom:16px;right:16px;width:360px;max-width:calc(100vw - 32px);max-height:60vh;overflow:auto;box-sizing:border-box;padding:16px;background:Canvas;color:CanvasText;border:2px solid currentColor;border-radius:8px";
  for (const button of [backButton,nextButton,retry,pauseButton,skipButton]) button.type = "button"; backButton.textContent = "Previous step"; nextButton.textContent = "Next step"; retry.textContent = "Retry target"; pauseButton.textContent = "Pause tour"; skipButton.textContent = "Skip tour"; panel.append(heading,body,status,backButton,nextButton,retry,pauseButton,skipButton); panel.hidden = true; document.body.append(panel);
  let progress = restoreTourProgress(null,options.version,ids), active = false, disposed = false, previous: HTMLElement | null = null, controller: AbortController | undefined, generation = 0, cleanup: (()=>void) | undefined;
  try { progress = restoreTourProgress(options.storage?.getItem(key) ?? null,options.version,ids); } catch {}
  const persist = () => { try { options.storage?.setItem(key,JSON.stringify(progress)); return true; } catch { status.textContent = "This step cannot be saved on this device. You can still continue."; return false; } };
  const pause = () => { generation++; controller?.abort(); controller = undefined; cleanup?.(); cleanup = undefined; active = false; panel.hidden = true; if (previous?.isConnected) previous.focus(); };
  const finish = (value: "completed" | "skipped") => { progress = {...progress,status:value}; persist(); pause(); try { options.onFinish?.(value); } catch {} };
  const show = async () => {
    if (!active || disposed) return; const current = ++generation; controller?.abort(); controller = new AbortController(); cleanup?.(); cleanup = undefined; const index = ids.indexOf(progress.stepId), step = steps[index]!; heading.textContent = step.title; body.textContent = step.body; status.textContent = `Step ${index+1} of ${steps.length}. Preparing…`; backButton.disabled = nextButton.disabled = retry.disabled = true;
    try { await step.prepare?.(controller.signal); if (!active || disposed || generation !== current) return; const target = step.target();
      if (!target || !target.isConnected || !target.getClientRects().length) { status.textContent = `Step ${index+1} of ${steps.length}. Target is unavailable. Retry or continue to the next step.`; retry.hidden = false; }
      else { const element = target as HTMLElement, outline = element.style?.getPropertyValue("outline"), priority = element.style?.getPropertyPriority("outline"), offset = element.style?.getPropertyValue("outline-offset"); if (element.style) { element.style.setProperty("outline","3px solid Highlight","important"); element.style.setProperty("outline-offset","4px"); cleanup = () => { if (outline) element.style.setProperty("outline",outline,priority); else element.style.removeProperty("outline"); if (offset) element.style.setProperty("outline-offset",offset); else element.style.removeProperty("outline-offset"); }; } target.scrollIntoView({block:"center",behavior:"instant"}); status.textContent = `Step ${index+1} of ${steps.length}.`; retry.hidden = true; }
      persist();
    } catch { if (active && !disposed && generation===current) { status.textContent = "Could not prepare this step. Retry or continue."; retry.hidden = false; } }
    finally { if (active && !disposed && generation===current) { backButton.disabled = index === 0; nextButton.disabled = retry.disabled = false; nextButton.textContent = index === steps.length-1 ? "Finish tour" : "Next step"; nextButton.focus(); } }
  };
  const next = async () => { if (!active || disposed) return; const index = ids.indexOf(progress.stepId); if (index===steps.length-1) finish("completed"); else { progress = {...progress,stepId:ids[index+1]!}; await show(); } };
  const back = async () => { if (!active || disposed) return; const index = ids.indexOf(progress.stepId); if (index>0) { progress = {...progress,stepId:ids[index-1]!}; await show(); } };
  nextButton.onclick = () => { void next(); }; backButton.onclick = () => { void back(); }; retry.onclick = () => { void show(); }; pauseButton.onclick = pause; skipButton.onclick = () => finish("skipped"); panel.addEventListener("keydown",event=>{if(event.key==="Escape"){event.preventDefault();pause();}});
  return { async start(restart=false) { if (disposed || active) return; if (restart) progress = restoreTourProgress(null,options.version,ids); if (progress.status !== "active") return; previous = document.activeElement as HTMLElement | null; active = true; panel.hidden = false; await show(); }, next, back, pause, skip() { if(active&&!disposed)finish("skipped"); }, progress:()=>({...progress}), dispose() { if(disposed)return;pause();disposed=true;panel.remove(); } };
}
