import { type Computed, type ReactiveSignal } from "./core.js";
import { type FieldController } from "./ui-fields.js";
import { type ChangeDetails, type Direction, type UiManifest } from "./ui-foundation.js";
import { type OpenChangeReason, type PopupOptions, type PopupPortalOptions } from "./ui-popups.js";
export interface SelectionItem<Value> { value: Value; label: string; disabled?: boolean; keywords?: readonly string[]; group?: string; }
export interface SelectionFilterOptions { locale?: string | string[]; sensitivity?: Intl.CollatorOptions["sensitivity"]; mode?: "contains" | "starts-with"; }
export declare function filterSelectionItems<Value>(items: readonly SelectionItem<Value>[], query: string, options?: SelectionFilterOptions): SelectionItem<Value>[];
export type SelectionPresentation = "popover" | "bottom-sheet" | "responsive";
export type SelectionReason = OpenChangeReason | "item-press" | "keyboard" | "clear" | "remove" | "input" | "reset" | "programmatic";
export type SelectionValue<Value> = Value | readonly Value[] | null;
export type AutocompleteFieldValue<Value> = string | readonly Value[];
export interface SelectOptions<Value> extends Omit<PopupOptions, "onOpenChange"> { items: readonly SelectionItem<Value>[]; multiple?: boolean; value?: SelectionValue<Value> | (() => SelectionValue<Value>); defaultValue?: SelectionValue<Value>; field?: FieldController<SelectionValue<Value>>; onValueChange?: (value: SelectionValue<Value>, details: ChangeDetails<SelectionReason>) => void; onOpenChange?: (open: boolean, details: ChangeDetails<OpenChangeReason>) => void; equals?: (left: Value, right: Value) => boolean; serialize?: (value: Value) => string; name?: string; form?: string; autoComplete?: string; required?: boolean; disabled?: boolean | (() => boolean); readOnly?: boolean | (() => boolean); loop?: boolean; direction?: Direction; closeOnSelect?: boolean; presentation?: SelectionPresentation; }
export interface SelectController<Value> { readonly id: string; readonly open: Computed<boolean>; readonly value: Computed<SelectionValue<Value>>; readonly highlightedIndex: ReactiveSignal<number>; readonly selectedItems: Computed<SelectionItem<Value>[]>; show(reason?: OpenChangeReason, event?: Event): boolean; hide(reason?: OpenChangeReason, event?: Event): boolean; clear(reason?: SelectionReason, event?: Event): boolean; select(value: Value, reason?: SelectionReason, event?: Event): boolean; label(): Record<string, unknown>; trigger(): Record<string, unknown>; valuePart(options?: { placeholder?: string }): Record<string, unknown>; icon(): Record<string, unknown>; isMounted(options?: PopupPortalOptions): boolean; portal(options?: PopupPortalOptions): Record<string, unknown>; backdrop(): Record<string, unknown>; positioner(): Record<string, unknown>; popup(): Record<string, unknown>; arrow(): Record<string, unknown>; list(): Record<string, unknown>; item(value: Value): Record<string, unknown>; itemText(value: Value): Record<string, unknown>; itemIndicator(value: Value): Record<string, unknown>; group(name: string): Record<string, unknown>; groupLabel(name: string): Record<string, unknown>; separator(): Record<string, unknown>; scrollUpArrow(): Record<string, unknown>; scrollDownArrow(): Record<string, unknown>; hiddenInputs(): Record<string, unknown>[]; manifest(): UiManifest; dispose(): void; }
export declare function createSelect<Value>(options: SelectOptions<Value>): SelectController<Value>;
export type CompletionMode = "none" | "list" | "both" | "inline";
export interface ComboboxOptions<Value> extends Omit<SelectOptions<Value>, "value" | "defaultValue" | "onValueChange" | "closeOnSelect"> { value?: SelectionValue<Value> | (() => SelectionValue<Value>); defaultValue?: SelectionValue<Value>; onValueChange?: (value: SelectionValue<Value>, details: ChangeDetails<SelectionReason>) => void; inputValue?: string | (() => string); defaultInputValue?: string; onInputValueChange?: (value: string, details: ChangeDetails<SelectionReason>) => void; filter?: (items: readonly SelectionItem<Value>[], query: string) => readonly SelectionItem<Value>[]; completionMode?: CompletionMode; autoHighlight?: boolean; openOnInputClick?: boolean; loopFocus?: boolean; allowCustomValue?: boolean; }
export interface AutocompleteOptions<Value> extends Omit<ComboboxOptions<Value>, "field"> { field?: FieldController<AutocompleteFieldValue<Value>>; keepHighlight?: boolean; }
export interface EditableSelectionInputOptions { id?: string; insidePopup?: boolean; ariaLabel?: string; }
export interface EditableSelectionTriggerOptions { id?: string; standalone?: boolean; agentId?: string; agentLabel?: string; }
export interface ComboboxController<Value> { readonly id: string; readonly open: Computed<boolean>; readonly value: Computed<SelectionValue<Value>>; readonly inputValue: Computed<string>; readonly filteredItems: Computed<readonly SelectionItem<Value>[]>; readonly highlightedIndex: ReactiveSignal<number>; show(reason?: OpenChangeReason, event?: Event): boolean; hide(reason?: OpenChangeReason, event?: Event): boolean; label(): Record<string, unknown>; input(options?: EditableSelectionInputOptions): Record<string, unknown>; inputGroup(): Record<string, unknown>; trigger(options?: EditableSelectionTriggerOptions): Record<string, unknown>; clear(): Record<string, unknown>; icon(): Record<string, unknown>; valuePart(options?: { placeholder?: string }): Record<string, unknown>; isMounted(options?: PopupPortalOptions): boolean; portal(options?: PopupPortalOptions): Record<string, unknown>; list(): Record<string, unknown>; popup(): Record<string, unknown>; positioner(): Record<string, unknown>; backdrop(): Record<string, unknown>; arrow(): Record<string, unknown>; status(): Record<string, unknown>; empty(): Record<string, unknown>; collection(): Record<string, unknown>; row(): Record<string, unknown>; item(value: Value): Record<string, unknown>; itemIndicator(value: Value): Record<string, unknown>; group(name: string): Record<string, unknown>; groupLabel(name: string): Record<string, unknown>; separator(): Record<string, unknown>; chips(): Record<string, unknown>; chip(value: Value): Record<string, unknown>; chipRemove(value: Value): Record<string, unknown>; hiddenInputs(): Record<string, unknown>[]; choose(value: Value, reason?: SelectionReason, event?: Event): boolean; setInput(value: string, reason?: SelectionReason, event?: Event): boolean; manifest(): UiManifest; dispose(): void; }
export declare function createCombobox<Value>(options: ComboboxOptions<Value>): ComboboxController<Value>;
export declare function createAutocomplete<Value>(options: AutocompleteOptions<Value>): ComboboxController<Value>;
